export const CURRICULUM_WEEKS = [
  {
    week: 1,
    themeEN: 'Professional Introductions',
    themeID: 'Perkenalan Profesional',
    descEN: 'Master greetings and self-introduction in business settings',
    descID: 'Kuasai sapaan dan perkenalan diri di lingkungan bisnis',
  },
  {
    week: 2,
    themeEN: 'Email Communication',
    themeID: 'Komunikasi Email',
    descEN: 'Write clear and professional emails in English',
    descID: 'Tulis email yang jelas dan profesional dalam bahasa Inggris',
  },
  {
    week: 3,
    themeEN: 'Meetings & Agendas',
    themeID: 'Rapat & Agenda',
    descEN: 'Run and participate in English-language meetings confidently',
    descID: 'Pimpin dan ikuti rapat dalam bahasa Inggris dengan percaya diri',
  },
  {
    week: 4,
    themeEN: 'Scheduling & Time Management',
    themeID: 'Penjadwalan & Manajemen Waktu',
    descEN: 'Discuss schedules, deadlines, and appointments professionally',
    descID: 'Bahas jadwal, tenggat waktu, dan janji temu secara profesional',
  },
  {
    week: 5,
    themeEN: 'Phone & Video Calls',
    themeID: 'Telepon & Video Call',
    descEN: 'Handle business calls with clarity and confidence',
    descID: 'Tangani panggilan bisnis dengan jelas dan percaya diri',
  },
  {
    week: 6,
    themeEN: 'Presentations & Pitching',
    themeID: 'Presentasi & Pitching',
    descEN: 'Deliver compelling presentations to clients and stakeholders',
    descID: 'Sampaikan presentasi yang meyakinkan kepada klien dan pemangku kepentingan',
  },
  {
    week: 7,
    themeEN: 'Negotiations',
    themeID: 'Negosiasi',
    descEN: 'Negotiate prices, contracts, and terms professionally in English',
    descID: 'Negosiasi harga, kontrak, dan syarat secara profesional dalam bahasa Inggris',
  },
  {
    week: 8,
    themeEN: 'Reports & Documentation',
    themeID: 'Laporan & Dokumentasi',
    descEN: 'Write and present business reports clearly',
    descID: 'Tulis dan sampaikan laporan bisnis dengan jelas',
  },
  {
    week: 9,
    themeEN: 'Customer Service',
    themeID: 'Layanan Pelanggan',
    descEN: 'Handle customer inquiries, complaints, and feedback professionally',
    descID: 'Tangani pertanyaan, keluhan, dan umpan balik pelanggan secara profesional',
  },
  {
    week: 10,
    themeEN: 'Leadership & Team Management',
    themeID: 'Kepemimpinan & Manajemen Tim',
    descEN: 'Use confident leadership language to motivate and direct teams',
    descID: 'Gunakan bahasa kepemimpinan yang percaya diri untuk memotivasi dan mengarahkan tim',
  },
  {
    week: 11,
    themeEN: 'Project Management',
    themeID: 'Manajemen Proyek',
    descEN: 'Discuss project timelines, milestones, and deliverables',
    descID: 'Diskusikan jadwal proyek, tonggak pencapaian, dan hasil kerja',
  },
  {
    week: 12,
    themeEN: 'Networking & Relationship Building',
    themeID: 'Jaringan & Membangun Relasi',
    descEN: 'Build professional relationships at events, trade fairs, and business trips',
    descID: 'Bangun hubungan profesional di acara, pameran dagang, dan perjalanan bisnis',
  },
  {
    week: 13,
    themeEN: 'Job Interviews & Career Growth',
    themeID: 'Wawancara Kerja & Pertumbuhan Karir',
    descEN: 'Perform confidently in English-language interviews and performance reviews',
    descID: 'Tampil percaya diri dalam wawancara dan evaluasi kinerja berbahasa Inggris',
  },
  {
    week: 14,
    themeEN: 'Problem Solving & Decision Making',
    themeID: 'Pemecahan Masalah & Pengambilan Keputusan',
    descEN: 'Discuss problems, propose solutions, and justify decisions in English',
    descID: 'Diskusikan masalah, usulkan solusi, dan justifikasi keputusan dalam bahasa Inggris',
  },
  {
    week: 15,
    themeEN: 'Sales & Business Development',
    themeID: 'Penjualan & Pengembangan Bisnis',
    descEN: 'Pitch products, close deals, and build client relationships',
    descID: 'Tawarkan produk, tutup kesepakatan, dan bangun hubungan klien',
  },
  {
    week: 16,
    themeEN: 'Finance & Budgeting',
    themeID: 'Keuangan & Penganggaran',
    descEN: 'Discuss budgets, costs, forecasts, and financial performance',
    descID: 'Diskusikan anggaran, biaya, perkiraan, dan kinerja keuangan',
  },
  {
    week: 17,
    themeEN: 'Operations & Logistics',
    themeID: 'Operasional & Logistik',
    descEN: 'Handle supply chain, shipping, and operational communication',
    descID: 'Tangani rantai pasokan, pengiriman, dan komunikasi operasional',
  },
  {
    week: 18,
    themeEN: 'Human Resources & Workplace Culture',
    themeID: 'SDM & Budaya Kerja',
    descEN: 'Navigate HR conversations, policies, and workplace dynamics',
    descID: 'Hadapi percakapan SDM, kebijakan, dan dinamika tempat kerja',
  },
  {
    week: 19,
    themeEN: 'International Business & Trade',
    themeID: 'Bisnis Internasional & Perdagangan',
    descEN: 'Communicate across borders — Singapore, Malaysia, China, and beyond',
    descID: 'Berkomunikasi lintas batas — Singapura, Malaysia, China, dan lebih jauh',
  },
  {
    week: 20,
    themeEN: 'Strategy & Planning',
    themeID: 'Strategi & Perencanaan',
    descEN: 'Discuss business strategy, goals, and long-term planning',
    descID: 'Diskusikan strategi bisnis, tujuan, dan perencanaan jangka panjang',
  },
  {
    week: 21,
    themeEN: 'Innovation & Technology',
    themeID: 'Inovasi & Teknologi',
    descEN: 'Talk about digital transformation, AI, and tech-driven business',
    descID: 'Bicarakan transformasi digital, AI, dan bisnis berbasis teknologi',
  },
  {
    week: 22,
    themeEN: 'Crisis Communication',
    themeID: 'Komunikasi Krisis',
    descEN: 'Handle difficult situations, bad news, and public communication professionally',
    descID: 'Tangani situasi sulit, berita buruk, dan komunikasi publik secara profesional',
  },
  {
    week: 23,
    themeEN: 'Advanced Business Communication',
    themeID: 'Komunikasi Bisnis Tingkat Lanjut',
    descEN: 'Polish tone, nuance, and persuasion in complex business interactions',
    descID: 'Sempurnakan nada, nuansa, dan persuasi dalam interaksi bisnis yang kompleks',
  },
  {
    week: 24,
    themeEN: 'Executive English',
    themeID: 'Bahasa Inggris Eksekutif',
    descEN: 'Communicate with authority, confidence, and strategic clarity',
    descID: 'Berkomunikasi dengan otoritas, kepercayaan diri, dan kejelasan strategis',
  },
  {
    week: 25,
    themeEN: 'Global Business & Cross-Cultural Communication',
    themeID: 'Bisnis Global & Komunikasi Lintas Budaya',
    descEN: 'Navigate cultural differences in international business settings',
    descID: 'Hadapi perbedaan budaya dalam lingkungan bisnis internasional',
  },
  {
    week: 26,
    themeEN: 'Mastery & Capstone',
    themeID: 'Penguasaan & Puncak Kurikulum',
    descEN: 'Integrate all skills — present, negotiate, lead, and communicate at the highest level',
    descID: 'Integrasikan semua keterampilan — presentasi, negosiasi, kepemimpinan, dan komunikasi di tingkat tertinggi',
  },
]
