// ─── GRAMMAR BANK ─────────────────────────────────────────────────────────────
// 10 grammar points, each with 5 exercises, bilingual, Batam business context

export const GRAMMAR_BANK = [
  {
    id: 'present_simple',
    week: 1,
    titleEN: 'Present Simple',
    titleID: 'Kalimat Sederhana Present Tense',
    ruleEN: 'Use Present Simple for habits, routines, facts, and permanent situations.',
    ruleID: 'Gunakan Present Simple untuk kebiasaan, rutinitas, fakta, dan situasi permanen.',
    structureEN: 'Subject + base verb (add -s/-es for he/she/it)',
    structureID: 'Subjek + kata kerja dasar (tambah -s/-es untuk he/she/it)',
    examplesEN: [
      'I work at the Batam industrial park every day.',
      'She sends the production report to Singapore every Monday.',
      'The ferry from Batam to Singapore departs at 8 AM.',
    ],
    examplesID: [
      'Saya bekerja di kawasan industri Batam setiap hari.',
      'Dia mengirim laporan produksi ke Singapura setiap Senin.',
      'Feri dari Batam ke Singapura berangkat pukul 8 pagi.',
    ],
    exercises: [
      {
        questionEN: 'She ___ (work) at the Singapore branch every Tuesday.',
        questionID: 'Dia ___ (bekerja) di cabang Singapura setiap Selasa.',
        answer: 'works',
        optionsEN: ['work', 'works', 'working', 'worked'],
        optionsID: ['bekerja', 'bekerja (she)', 'sedang bekerja', 'sudah bekerja'],
      },
      {
        questionEN: 'Our factory ___ (produce) 2,000 units per day.',
        questionID: 'Pabrik kami ___ (memproduksi) 2.000 unit per hari.',
        answer: 'produces',
        optionsEN: ['produce', 'produces', 'is producing', 'produced'],
        optionsID: ['memproduksi', 'memproduksi (it)', 'sedang memproduksi', 'telah memproduksi'],
      },
      {
        questionEN: 'I ___ (send) the invoice to the client every Friday.',
        questionID: 'Saya ___ (mengirim) faktur kepada klien setiap Jumat.',
        answer: 'send',
        optionsEN: ['sends', 'send', 'sent', 'sending'],
        optionsID: ['mengirim (she)', 'mengirim', 'dikirim', 'sedang mengirim'],
      },
      {
        questionEN: 'The manager ___ (not approve) late submissions.',
        questionID: 'Manajer ___ (tidak menyetujui) pengajuan yang terlambat.',
        answer: "doesn't approve",
        optionsEN: ["doesn't approve", "don't approve", "not approves", "isn't approving"],
        optionsID: ['tidak menyetujui (she)', 'tidak menyetujui (I)', 'tidak menyetujui (salah)', 'tidak sedang menyetujui'],
      },
      {
        questionEN: '___ the Singapore office ___ (open) on Saturdays?',
        questionID: 'Apakah kantor Singapura ___ (buka) pada hari Sabtu?',
        answer: 'Does / open',
        optionsEN: ['Does / open', 'Do / opens', 'Is / opening', 'Did / open'],
        optionsID: ['Does / buka', 'Do / buka', 'Is / sedang buka', 'Did / buka'],
      },
    ],
  },
  {
    id: 'present_continuous',
    week: 2,
    titleEN: 'Present Continuous',
    titleID: 'Kalimat Present Continuous',
    ruleEN: 'Use Present Continuous for actions happening right now or ongoing temporary situations.',
    ruleID: 'Gunakan Present Continuous untuk tindakan yang sedang terjadi sekarang atau situasi sementara yang sedang berlangsung.',
    structureEN: 'Subject + am/is/are + verb-ing',
    structureID: 'Subjek + am/is/are + kata kerja-ing',
    examplesEN: [
      'I am currently reviewing the contract with legal.',
      'The team is working on the Singapore proposal right now.',
      'We are expanding our warehouse capacity this quarter.',
    ],
    examplesID: [
      'Saya sedang meninjau kontrak dengan bagian hukum.',
      'Tim sedang mengerjakan proposal Singapura sekarang.',
      'Kami sedang memperluas kapasitas gudang kuartal ini.',
    ],
    exercises: [
      {
        questionEN: 'She ___ (prepare) the quarterly report at the moment.',
        questionID: 'Dia ___ (mempersiapkan) laporan kuartalan saat ini.',
        answer: 'is preparing',
        optionsEN: ['prepares', 'is preparing', 'prepared', 'has prepared'],
        optionsID: ['mempersiapkan', 'sedang mempersiapkan', 'sudah mempersiapkan', 'telah mempersiapkan'],
      },
      {
        questionEN: 'We ___ (negotiate) a new deal with our Malaysian supplier.',
        questionID: 'Kami ___ (bernegosiasi) kesepakatan baru dengan pemasok Malaysia kami.',
        answer: 'are negotiating',
        optionsEN: ['negotiate', 'are negotiating', 'were negotiating', 'have negotiated'],
        optionsID: ['bernegosiasi', 'sedang bernegosiasi', 'sedang bernegosiasi (lalu)', 'telah bernegosiasi'],
      },
      {
        questionEN: 'The director ___ (not attend) the meeting because he is travelling.',
        questionID: 'Direktur ___ (tidak hadir) di rapat karena dia sedang bepergian.',
        answer: 'is not attending',
        optionsEN: ['does not attend', 'is not attending', 'will not attend', 'has not attended'],
        optionsID: ['tidak hadir (kebiasaan)', 'tidak sedang hadir', 'tidak akan hadir', 'belum hadir'],
      },
      {
        questionEN: '___ the Singapore client ___ (visit) the factory this week?',
        questionID: 'Apakah klien Singapura ___ (mengunjungi) pabrik minggu ini?',
        answer: 'Is / visiting',
        optionsEN: ['Does / visit', 'Is / visiting', 'Will / visit', 'Has / visited'],
        optionsID: ['Does / kunjungi', 'Is / sedang kunjungi', 'Will / akan kunjungi', 'Has / sudah kunjungi'],
      },
      {
        questionEN: 'I ___ (look) for a more reliable shipping partner.',
        questionID: 'Saya ___ (mencari) mitra pengiriman yang lebih andal.',
        answer: 'am looking',
        optionsEN: ['look', 'am looking', 'looked', 'have looked'],
        optionsID: ['mencari', 'sedang mencari', 'sudah mencari', 'telah mencari'],
      },
    ],
  },
  {
    id: 'simple_past',
    week: 4,
    titleEN: 'Simple Past',
    titleID: 'Kalimat Simple Past Tense',
    ruleEN: 'Use Simple Past for completed actions at a specific time in the past.',
    ruleID: 'Gunakan Simple Past untuk tindakan yang sudah selesai pada waktu tertentu di masa lalu.',
    structureEN: 'Subject + past verb (regular: add -ed; irregular verbs must be memorised)',
    structureID: 'Subjek + kata kerja past (reguler: tambah -ed; kata kerja tidak reguler harus dihafal)',
    examplesEN: [
      'We signed the contract with the Singapore client last Thursday.',
      'The shipment arrived two days late because of customs delays.',
      'I attended the regional trade fair in Singapore last month.',
    ],
    examplesID: [
      'Kami menandatangani kontrak dengan klien Singapura Kamis lalu.',
      'Kiriman tiba dua hari terlambat karena penundaan bea cukai.',
      'Saya menghadiri pameran dagang regional di Singapura bulan lalu.',
    ],
    exercises: [
      {
        questionEN: 'The manager ___ (approve) the budget last week.',
        questionID: 'Manajer ___ (menyetujui) anggaran minggu lalu.',
        answer: 'approved',
        optionsEN: ['approve', 'approved', 'has approved', 'approves'],
        optionsID: ['menyetujui', 'menyetujui (kemarin)', 'telah menyetujui', 'menyetujui (kebiasaan)'],
      },
      {
        questionEN: 'We ___ (receive) the purchase order from Singapore yesterday.',
        questionID: 'Kami ___ (menerima) pesanan pembelian dari Singapura kemarin.',
        answer: 'received',
        optionsEN: ['receive', 'received', 'are receiving', 'will receive'],
        optionsID: ['menerima', 'menerima (kemarin)', 'sedang menerima', 'akan menerima'],
      },
      {
        questionEN: 'She ___ (not attend) the conference call because of a network issue.',
        questionID: 'Dia ___ (tidak hadir) di konferensi call karena masalah jaringan.',
        answer: "didn't attend",
        optionsEN: ["doesn't attend", "didn't attend", "wasn't attending", "hadn't attended"],
        optionsID: ['tidak hadir (kebiasaan)', 'tidak hadir (kemarin)', 'tidak sedang hadir', 'belum pernah hadir'],
      },
      {
        questionEN: '___ the team ___ (meet) the production deadline last quarter?',
        questionID: 'Apakah tim ___ (memenuhi) tenggat produksi kuartal lalu?',
        answer: 'Did / meet',
        optionsEN: ['Does / meet', 'Did / meet', 'Has / met', 'Was / meeting'],
        optionsID: ['Does / penuhi', 'Did / penuhi', 'Has / sudah penuhi', 'Was / sedang penuhi'],
      },
      {
        questionEN: 'The client ___ (send) a complaint email about the delivery delay.',
        questionID: 'Klien ___ (mengirim) email keluhan tentang keterlambatan pengiriman.',
        answer: 'sent',
        optionsEN: ['send', 'sent', 'sends', 'is sending'],
        optionsID: ['mengirim', 'mengirim (kemarin)', 'mengirim (kebiasaan)', 'sedang mengirim'],
      },
    ],
  },
  {
    id: 'future_will_going_to',
    week: 5,
    titleEN: 'Future: Will vs. Going To',
    titleID: 'Future: Will vs. Going To',
    ruleEN: 'Use "will" for decisions made at the moment of speaking or promises. Use "going to" for plans made in advance.',
    ruleID: 'Gunakan "will" untuk keputusan yang dibuat saat berbicara atau janji. Gunakan "going to" untuk rencana yang sudah disiapkan sebelumnya.',
    structureEN: '"Will": Subject + will + base verb | "Going to": Subject + am/is/are + going to + base verb',
    structureID: '"Will": Subjek + will + kata kerja dasar | "Going to": Subjek + am/is/are + going to + kata kerja dasar',
    examplesEN: [
      'I will send you the report right away. (decision just made)',
      'We are going to launch the new product line in Q4. (pre-planned)',
      'She will handle the Singapore account while I am on leave.',
    ],
    examplesID: [
      'Saya akan segera mengirimkan laporan. (keputusan baru saja dibuat)',
      'Kami akan meluncurkan lini produk baru di Q4. (sudah direncanakan)',
      'Dia akan menangani akun Singapura selama saya cuti.',
    ],
    exercises: [
      {
        questionEN: 'A: The printer is broken. B: Don\'t worry, I ___ (call) the technician now.',
        questionID: 'A: Printer rusak. B: Jangan khawatir, saya ___ (menelepon) teknisi sekarang.',
        answer: "will call",
        optionsEN: ['will call', 'am going to call', 'call', 'am calling'],
        optionsID: ['akan menelepon (spontan)', 'akan menelepon (rencana)', 'menelepon', 'sedang menelepon'],
      },
      {
        questionEN: 'We ___ (expand) our Singapore office next year — it\'s already approved.',
        questionID: 'Kami ___ (memperluas) kantor Singapura tahun depan — sudah disetujui.',
        answer: 'are going to expand',
        optionsEN: ['will expand', 'are going to expand', 'expand', 'are expanding'],
        optionsID: ['akan memperluas (spontan)', 'akan memperluas (rencana)', 'memperluas', 'sedang memperluas'],
      },
      {
        questionEN: 'I promise I ___ (deliver) the proposal before Friday.',
        questionID: 'Saya berjanji akan ___ (mengirimkan) proposal sebelum Jumat.',
        answer: 'will deliver',
        optionsEN: ['will deliver', 'am going to deliver', 'deliver', 'delivered'],
        optionsID: ['akan mengirimkan (janji)', 'akan mengirimkan (rencana)', 'mengirimkan', 'sudah mengirimkan'],
      },
      {
        questionEN: 'The CEO ___ (announce) the restructuring plan at the all-hands meeting next Friday.',
        questionID: 'CEO ___ (mengumumkan) rencana restrukturisasi di rapat besar Jumat depan.',
        answer: 'is going to announce',
        optionsEN: ['will announce', 'is going to announce', 'announces', 'announced'],
        optionsID: ['akan mengumumkan (spontan)', 'akan mengumumkan (rencana)', 'mengumumkan (kebiasaan)', 'sudah mengumumkan'],
      },
      {
        questionEN: 'If the client calls, I ___ (let) you know immediately.',
        questionID: 'Jika klien menelepon, saya ___ (memberi tahu) Anda segera.',
        answer: 'will let',
        optionsEN: ['will let', 'am going to let', 'let', 'letting'],
        optionsID: ['akan memberi tahu', 'akan memberi tahu (rencana)', 'memberi tahu', 'sedang memberi tahu'],
      },
    ],
  },
  {
    id: 'modal_verbs',
    week: 6,
    titleEN: 'Modal Verbs: Can / Should / Must',
    titleID: 'Kata Kerja Modal: Can / Should / Must',
    ruleEN: '"Can" = ability or possibility. "Should" = advice or recommendation. "Must" = strong obligation or necessity.',
    ruleID: '"Can" = kemampuan atau kemungkinan. "Should" = saran atau rekomendasi. "Must" = kewajiban kuat atau keharusan.',
    structureEN: 'Subject + modal (can/should/must) + base verb (no -s, no -ing, no -ed)',
    structureID: 'Subjek + modal (can/should/must) + kata kerja dasar (tanpa -s, -ing, atau -ed)',
    examplesEN: [
      'Can you send me the updated invoice? (polite request / ability)',
      'You should confirm the meeting time with the Singapore team. (advice)',
      'All staff must wear PPE in the production area. (obligation)',
    ],
    examplesID: [
      'Bisakah Anda mengirimkan faktur terbaru? (permintaan sopan / kemampuan)',
      'Anda sebaiknya mengonfirmasi waktu rapat dengan tim Singapura. (saran)',
      'Semua staf harus memakai APD di area produksi. (kewajiban)',
    ],
    exercises: [
      {
        questionEN: 'All export documents ___ be submitted 48 hours before shipment.',
        questionID: 'Semua dokumen ekspor ___ diserahkan 48 jam sebelum pengiriman.',
        answer: 'must',
        optionsEN: ['can', 'should', 'must', 'will'],
        optionsID: ['bisa', 'sebaiknya', 'harus (wajib)', 'akan'],
      },
      {
        questionEN: 'You ___ follow up with the client after a week of no response.',
        questionID: 'Anda ___ menindaklanjuti klien setelah seminggu tidak ada respons.',
        answer: 'should',
        optionsEN: ['can', 'should', 'must', 'might'],
        optionsID: ['bisa', 'sebaiknya', 'harus (wajib)', 'mungkin'],
      },
      {
        questionEN: 'Our Batam factory ___ produce 3,000 units per shift at full capacity.',
        questionID: 'Pabrik Batam kami ___ memproduksi 3.000 unit per giliran kerja pada kapasitas penuh.',
        answer: 'can',
        optionsEN: ['can', 'should', 'must', 'will'],
        optionsID: ['bisa', 'sebaiknya', 'harus', 'akan'],
      },
      {
        questionEN: 'You ___ not share confidential client data with external parties.',
        questionID: 'Anda ___ tidak boleh membagikan data klien rahasia kepada pihak eksternal.',
        answer: 'must',
        optionsEN: ['can', 'should', 'must', 'might'],
        optionsID: ['bisa', 'sebaiknya', 'harus (wajib)', 'mungkin'],
      },
      {
        questionEN: 'We ___ consider offering flexible payment terms to attract larger clients.',
        questionID: 'Kita ___ mempertimbangkan untuk menawarkan syarat pembayaran yang fleksibel untuk menarik klien yang lebih besar.',
        answer: 'should',
        optionsEN: ['can', 'should', 'must', 'will'],
        optionsID: ['bisa', 'sebaiknya', 'harus (wajib)', 'akan'],
      },
    ],
  },
  {
    id: 'comparatives',
    week: 8,
    titleEN: 'Comparatives & Superlatives',
    titleID: 'Kalimat Perbandingan dan Superlatif',
    ruleEN: 'Use comparatives to compare two things. Use superlatives to compare one thing against all others in a group.',
    ruleID: 'Gunakan comparatives untuk membandingkan dua hal. Gunakan superlatives untuk membandingkan satu hal dengan semua yang lain dalam kelompok.',
    structureEN: 'Comparative: adj + -er / more + adj + than | Superlative: the + adj + -est / the most + adj',
    structureID: 'Comparative: adj + -er / more + adj + than | Superlative: the + adj + -est / the most + adj',
    examplesEN: [
      'Our new production line is faster than the old one.',
      'Batam labour costs are lower than Singapore\'s.',
      'This is the most efficient logistics solution we have tested.',
    ],
    examplesID: [
      'Lini produksi baru kami lebih cepat dari yang lama.',
      'Biaya tenaga kerja Batam lebih rendah dari Singapura.',
      'Ini adalah solusi logistik paling efisien yang pernah kami uji.',
    ],
    exercises: [
      {
        questionEN: 'The new supplier is ___ (reliable) than our previous one.',
        questionID: 'Pemasok baru lebih ___ (andal) dari yang sebelumnya.',
        answer: 'more reliable',
        optionsEN: ['reliably', 'more reliable', 'most reliable', 'reliablest'],
        optionsID: ['andal', 'lebih andal', 'paling andal', 'lebih andal (salah)'],
      },
      {
        questionEN: 'This is ___ (bad) quarter we have had in three years.',
        questionID: 'Ini adalah kuartal ___ (buruk) yang pernah kami alami dalam tiga tahun.',
        answer: 'the worst',
        optionsEN: ['worse', 'the worst', 'the most bad', 'more bad'],
        optionsID: ['lebih buruk', 'paling buruk', 'paling buruk (salah)', 'lebih buruk (salah)'],
      },
      {
        questionEN: 'Shipping by sea is ___ (cheap) than air freight but takes longer.',
        questionID: 'Pengiriman laut ___ (murah) daripada kargo udara tetapi membutuhkan waktu lebih lama.',
        answer: 'cheaper',
        optionsEN: ['cheap', 'cheaper', 'cheapest', 'more cheap'],
        optionsID: ['murah', 'lebih murah', 'paling murah', 'lebih murah (salah)'],
      },
      {
        questionEN: 'Which vendor offers ___ (competitive) pricing for bulk orders?',
        questionID: 'Vendor mana yang menawarkan harga ___ (kompetitif) untuk pesanan massal?',
        answer: 'the most competitive',
        optionsEN: ['more competitive', 'the most competitive', 'competitive', 'competitiver'],
        optionsID: ['lebih kompetitif', 'paling kompetitif', 'kompetitif', 'lebih kompetitif (salah)'],
      },
      {
        questionEN: 'Our Batam plant is ___ (large) than the one in Johor Bahru.',
        questionID: 'Pabrik Batam kami ___ (besar) dari yang ada di Johor Bahru.',
        answer: 'larger',
        optionsEN: ['large', 'larger', 'the largest', 'more large'],
        optionsID: ['besar', 'lebih besar', 'paling besar', 'lebih besar (salah)'],
      },
    ],
  },
  {
    id: 'first_conditional',
    week: 9,
    titleEN: 'First Conditional',
    titleID: 'Kalimat Kondisional Pertama',
    ruleEN: 'Use the First Conditional for real, likely future situations and their probable results.',
    ruleID: 'Gunakan Kondisional Pertama untuk situasi masa depan yang nyata dan kemungkinan hasilnya.',
    structureEN: 'If + Present Simple, will + base verb',
    structureID: 'If + Present Simple, will + kata kerja dasar',
    examplesEN: [
      'If we miss the deadline, the client will cancel the order.',
      'If the factory passes the audit, we will secure the Singapore contract.',
      'If you send the invoice today, they will process the payment by Friday.',
    ],
    examplesID: [
      'Jika kita melewati tenggat waktu, klien akan membatalkan pesanan.',
      'Jika pabrik lulus audit, kita akan mendapatkan kontrak Singapura.',
      'Jika Anda mengirim faktur hari ini, mereka akan memproses pembayaran sebelum Jumat.',
    ],
    exercises: [
      {
        questionEN: 'If the shipment ___ (arrive) on time, we ___ (meet) the delivery commitment.',
        questionID: 'Jika pengiriman ___ (tiba) tepat waktu, kami ___ (memenuhi) komitmen pengiriman.',
        answer: 'arrives / will meet',
        optionsEN: ['arrives / will meet', 'will arrive / meet', 'arrived / would meet', 'arrive / will meet'],
        optionsID: ['tiba / akan memenuhi', 'akan tiba / memenuhi', 'tiba (lalu) / akan memenuhi', 'tiba / akan memenuhi'],
      },
      {
        questionEN: 'If they ___ (not pay) the invoice, we ___ (stop) supplying materials.',
        questionID: 'Jika mereka ___ (tidak membayar) faktur, kami ___ (menghentikan) pasokan bahan.',
        answer: "don't pay / will stop",
        optionsEN: ["don't pay / will stop", "won't pay / stop", "didn't pay / would stop", "don't pay / stop"],
        optionsID: ['tidak bayar / akan hentikan', 'tidak akan bayar / hentikan', 'tidak bayar (lalu) / akan hentikan', 'tidak bayar / hentikan'],
      },
      {
        questionEN: 'If the manager ___ (approve) the budget, we ___ (start) the project next month.',
        questionID: 'Jika manajer ___ (menyetujui) anggaran, kami ___ (memulai) proyek bulan depan.',
        answer: 'approves / will start',
        optionsEN: ['approves / will start', 'will approve / start', 'approved / would start', 'approve / will start'],
        optionsID: ['menyetujui / akan mulai', 'akan menyetujui / mulai', 'menyetujui (lalu) / akan mulai', 'menyetujui / akan mulai'],
      },
      {
        questionEN: 'The Singapore client ___ (be) impressed if we ___ (deliver) ahead of schedule.',
        questionID: 'Klien Singapura ___ (terkesan) jika kami ___ (mengantarkan) lebih awal dari jadwal.',
        answer: 'will be / deliver',
        optionsEN: ['will be / deliver', 'is / will deliver', 'would be / delivered', 'will be / delivers'],
        optionsID: ['akan terkesan / antarkan', 'terkesan / akan antarkan', 'akan terkesan / antarkan (lalu)', 'akan terkesan / antarkan (she)'],
      },
      {
        questionEN: 'If the team ___ (work) overtime this weekend, we ___ (finish) the order in time.',
        questionID: 'Jika tim ___ (bekerja) lembur akhir pekan ini, kami ___ (menyelesaikan) pesanan tepat waktu.',
        answer: 'works / will finish',
        optionsEN: ['works / will finish', 'will work / finish', 'worked / would finish', 'work / will finish'],
        optionsID: ['bekerja / akan selesai', 'akan bekerja / selesai', 'bekerja (lalu) / akan selesai', 'bekerja / akan selesai'],
      },
    ],
  },
  {
    id: 'passive_voice',
    week: 11,
    titleEN: 'Passive Voice',
    titleID: 'Kalimat Pasif',
    ruleEN: 'Use Passive Voice when the action is more important than who does it, or when the doer is unknown or unimportant.',
    ruleID: 'Gunakan Kalimat Pasif ketika tindakan lebih penting dari siapa yang melakukannya, atau ketika pelaku tidak diketahui atau tidak penting.',
    structureEN: 'Subject + am/is/are/was/were + past participle (+ by + agent, optional)',
    structureID: 'Subjek + am/is/are/was/were + kata kerja past participle (+ by + pelaku, opsional)',
    examplesEN: [
      'The report was approved by the director yesterday.',
      'All export shipments are inspected by customs at Batu Ampar port.',
      'The new contract will be signed next week.',
    ],
    examplesID: [
      'Laporan disetujui oleh direktur kemarin.',
      'Semua pengiriman ekspor diperiksa oleh bea cukai di pelabuhan Batu Ampar.',
      'Kontrak baru akan ditandatangani minggu depan.',
    ],
    exercises: [
      {
        questionEN: 'The invoice ___ (send) to the Singapore client this morning.',
        questionID: 'Faktur ___ (dikirim) ke klien Singapura pagi ini.',
        answer: 'was sent',
        optionsEN: ['sent', 'was sent', 'is sent', 'has sent'],
        optionsID: ['dikirim', 'sudah dikirim (lalu)', 'dikirim (sekarang)', 'mengirim'],
      },
      {
        questionEN: 'All production targets ___ (review) by the operations manager weekly.',
        questionID: 'Semua target produksi ___ (ditinjau) oleh manajer operasional setiap minggu.',
        answer: 'are reviewed',
        optionsEN: ['review', 'are reviewed', 'were reviewed', 'have reviewed'],
        optionsID: ['meninjau', 'ditinjau (rutin)', 'ditinjau (lalu)', 'meninjau (sudah)'],
      },
      {
        questionEN: 'The new machinery ___ (install) at the Batam factory next month.',
        questionID: 'Mesin baru ___ (dipasang) di pabrik Batam bulan depan.',
        answer: 'will be installed',
        optionsEN: ['will install', 'will be installed', 'is installed', 'was installed'],
        optionsID: ['akan memasang', 'akan dipasang', 'dipasang (sekarang)', 'dipasang (lalu)'],
      },
      {
        questionEN: 'The defective units ___ (replace) by the supplier at no cost.',
        questionID: 'Unit yang cacat ___ (diganti) oleh pemasok tanpa biaya.',
        answer: 'were replaced',
        optionsEN: ['replaced', 'were replaced', 'are replaced', 'have replaced'],
        optionsID: ['mengganti', 'sudah diganti (lalu)', 'diganti (rutin)', 'mengganti (sudah)'],
      },
      {
        questionEN: 'The final proposal ___ (submit) to the Singapore government agency last Friday.',
        questionID: 'Proposal akhir ___ (diserahkan) ke lembaga pemerintah Singapura Jumat lalu.',
        answer: 'was submitted',
        optionsEN: ['submitted', 'was submitted', 'has been submitted', 'is submitted'],
        optionsID: ['menyerahkan', 'diserahkan (lalu)', 'telah diserahkan', 'diserahkan (sekarang)'],
      },
    ],
  },
  {
    id: 'present_perfect',
    week: 13,
    titleEN: 'Present Perfect',
    titleID: 'Kalimat Present Perfect',
    ruleEN: 'Use Present Perfect for past actions with a connection to the present — especially experience, recent events, or unfinished time frames.',
    ruleID: 'Gunakan Present Perfect untuk tindakan masa lalu yang terhubung dengan sekarang — terutama pengalaman, kejadian baru-baru ini, atau kerangka waktu yang belum selesai.',
    structureEN: 'Subject + have/has + past participle',
    structureID: 'Subjek + have/has + kata kerja past participle',
    examplesEN: [
      'We have already sent the revised proposal to the client.',
      'She has worked with Singapore-based companies for over ten years.',
      'The team has not yet completed the factory audit.',
    ],
    examplesID: [
      'Kami sudah mengirim proposal yang direvisi ke klien.',
      'Dia sudah bekerja dengan perusahaan berbasis Singapura selama lebih dari sepuluh tahun.',
      'Tim belum menyelesaikan audit pabrik.',
    ],
    exercises: [
      {
        questionEN: 'We ___ (just / receive) confirmation from the Singapore buyer.',
        questionID: 'Kami ___ (baru saja / menerima) konfirmasi dari pembeli Singapura.',
        answer: 'have just received',
        optionsEN: ['just received', 'have just received', 'just receive', 'received just'],
        optionsID: ['baru saja terima (simple past)', 'baru saja menerima (present perfect)', 'baru saja terima (salah)', 'salah urutan'],
      },
      {
        questionEN: 'She ___ (work) in the export department for five years.',
        questionID: 'Dia ___ (bekerja) di departemen ekspor selama lima tahun.',
        answer: 'has worked',
        optionsEN: ['worked', 'has worked', 'is working', 'works'],
        optionsID: ['bekerja (simple past)', 'sudah bekerja (present perfect)', 'sedang bekerja', 'bekerja (kebiasaan)'],
      },
      {
        questionEN: 'The board ___ (not approve) the expansion plan yet.',
        questionID: 'Dewan ___ (belum menyetujui) rencana ekspansi.',
        answer: 'has not approved',
        optionsEN: ['did not approve', 'has not approved', 'is not approving', 'will not approve'],
        optionsID: ['tidak menyetujui (simple past)', 'belum menyetujui (present perfect)', 'tidak sedang menyetujui', 'tidak akan menyetujui'],
      },
      {
        questionEN: '___ you ever ___ (negotiate) a contract in English?',
        questionID: 'Pernahkah Anda ___ (bernegosiasi) kontrak dalam bahasa Inggris?',
        answer: 'Have / negotiated',
        optionsEN: ['Did / negotiate', 'Have / negotiated', 'Are / negotiating', 'Do / negotiate'],
        optionsID: ['Apakah (simple past)', 'Pernahkah (present perfect)', 'Apakah sedang', 'Apakah (kebiasaan)'],
      },
      {
        questionEN: 'Our company ___ (expand) into three new markets since 2022.',
        questionID: 'Perusahaan kami ___ (berkembang) ke tiga pasar baru sejak 2022.',
        answer: 'has expanded',
        optionsEN: ['expanded', 'has expanded', 'is expanding', 'expands'],
        optionsID: ['berkembang (simple past)', 'sudah berkembang (present perfect)', 'sedang berkembang', 'berkembang (kebiasaan)'],
      },
    ],
  },
  {
    id: 'reported_speech',
    week: 16,
    titleEN: 'Reported Speech',
    titleID: 'Kalimat Tidak Langsung (Reported Speech)',
    ruleEN: 'Use Reported Speech to tell someone what another person said. Verbs usually shift one tense back.',
    ruleID: 'Gunakan Reported Speech untuk memberitahu seseorang apa yang dikatakan orang lain. Kata kerja biasanya mundur satu tense.',
    structureEN: 'Direct: "I will send the report." → Reported: She said (that) she would send the report.',
    structureID: 'Langsung: "I will send the report." → Tidak Langsung: Dia berkata bahwa dia akan mengirim laporan.',
    examplesEN: [
      '"We need more time." → The client said they needed more time.',
      '"I will visit the factory next week." → He said he would visit the factory the following week.',
      '"The shipment has been delayed." → She told us the shipment had been delayed.',
    ],
    examplesID: [
      '"We need more time." → Klien mengatakan mereka membutuhkan lebih banyak waktu.',
      '"I will visit the factory next week." → Dia berkata akan mengunjungi pabrik minggu berikutnya.',
      '"The shipment has been delayed." → Dia memberitahu kami bahwa pengiriman sudah terlambat.',
    ],
    exercises: [
      {
        questionEN: 'Direct: "We are expanding to Singapore." Reported: The CEO said they ___ expanding to Singapore.',
        questionID: 'Langsung: "We are expanding to Singapore." Tidak langsung: CEO berkata mereka ___ ke Singapura.',
        answer: 'were',
        optionsEN: ['are', 'were', 'will be', 'have been'],
        optionsID: ['sedang (present)', 'sedang (reported, past)', 'akan', 'sudah'],
      },
      {
        questionEN: 'Direct: "I will call you tomorrow." Reported: She said she ___ call me the next day.',
        questionID: 'Langsung: "I will call you tomorrow." Tidak langsung: Dia berkata akan menelepon saya keesokan harinya.',
        answer: 'would',
        optionsEN: ['will', 'would', 'might', 'should'],
        optionsID: ['akan (direct)', 'akan (reported)', 'mungkin', 'sebaiknya'],
      },
      {
        questionEN: 'Direct: "The client has approved the contract." Reported: He told me the client ___ the contract.',
        questionID: 'Langsung: "The client has approved the contract." Tidak langsung: Dia memberitahu saya klien ___ kontrak.',
        answer: 'had approved',
        optionsEN: ['has approved', 'had approved', 'approved', 'approves'],
        optionsID: ['sudah menyetujui (present perfect)', 'sudah menyetujui (reported)', 'menyetujui (simple past)', 'menyetujui (kebiasaan)'],
      },
      {
        questionEN: 'Direct: "We cannot meet the deadline." Reported: The supplier said they ___ meet the deadline.',
        questionID: 'Langsung: "We cannot meet the deadline." Tidak langsung: Pemasok berkata mereka ___ memenuhi tenggat.',
        answer: 'could not',
        optionsEN: ['cannot', 'could not', 'will not', 'should not'],
        optionsID: ['tidak bisa (direct)', 'tidak bisa (reported)', 'tidak akan', 'tidak seharusnya'],
      },
      {
        questionEN: 'Direct: "The meeting is at 3 PM." Reported: He said the meeting ___ at 3 PM.',
        questionID: 'Langsung: "The meeting is at 3 PM." Tidak langsung: Dia berkata rapat ___ pukul 3 sore.',
        answer: 'was',
        optionsEN: ['is', 'was', 'will be', 'has been'],
        optionsID: ['adalah (direct)', 'adalah (reported)', 'akan', 'sudah'],
      },
    ],
  },
]
