// ─── VOCAB BANK ───────────────────────────────────────────────────────────────
// Lower = A1-A2 (30 words), Medium = B1-B2 (30 words), High = C1 (20 words)
// All tied to Batam business / Indonesia-Singapore trade zone context

export const VOCAB_BANK = {
  lower: [
    {
      id: 'schedule',
      week: 1,
      word: 'SCHEDULE',
      phonetic: '/ˈsked.juːl/',
      meaningID: 'Jadwal / Menjadwalkan',
      meaningEN: 'A plan that shows what events will happen and when',
      sentenceEN: 'Can we schedule a meeting for Monday?',
      sentenceID: 'Bisakah kita jadwalkan rapat hari Senin?',
      sentenceEN2: 'I need to schedule time for the client presentation.',
      sentenceID2: 'Saya perlu menjadwalkan waktu untuk presentasi klien.',
      tipEN: 'Commonly used in Batam–Singapore business coordination.',
      tipID: 'Umum digunakan dalam koordinasi bisnis Batam–Singapura.',
    },
    {
      id: 'meeting',
      week: 1,
      word: 'MEETING',
      phonetic: '/ˈmiː.tɪŋ/',
      meaningID: 'Rapat / Pertemuan',
      meaningEN: 'A gathering of people to discuss business matters',
      sentenceEN: 'The meeting starts at 9 AM in the conference room.',
      sentenceID: 'Rapat dimulai pukul 9 pagi di ruang konferensi.',
      sentenceEN2: 'We have a meeting with the Singapore team this afternoon.',
      sentenceID2: 'Kami ada rapat dengan tim Singapura sore ini.',
      tipEN: 'Always confirm the meeting language — English or Indonesian — before it starts.',
      tipID: 'Selalu konfirmasi bahasa rapat — Inggris atau Indonesia — sebelum dimulai.',
    },
    {
      id: 'email',
      week: 2,
      word: 'EMAIL',
      phonetic: '/ˈiː.meɪl/',
      meaningID: 'Email / Surat Elektronik',
      meaningEN: 'A message sent electronically, used for professional communication',
      sentenceEN: 'Please send me an email with the project details.',
      sentenceID: 'Tolong kirimkan saya email dengan detail proyeknya.',
      sentenceEN2: 'I will reply to your email by end of day.',
      sentenceID2: 'Saya akan membalas email Anda sebelum akhir hari.',
      tipEN: 'Keep business emails short and clear. Start with "Dear" or "Hi [Name]".',
      tipID: 'Buat email bisnis singkat dan jelas. Mulai dengan "Dear" atau "Hi [Nama]".',
    },
    {
      id: 'report',
      week: 2,
      word: 'REPORT',
      phonetic: '/rɪˈpɔːt/',
      meaningID: 'Laporan',
      meaningEN: 'A formal document describing facts, results, or progress',
      sentenceEN: 'I need to submit the weekly report by Friday.',
      sentenceID: 'Saya harus menyerahkan laporan mingguan sebelum Jumat.',
      sentenceEN2: 'The production report shows 95% efficiency this month.',
      sentenceID2: 'Laporan produksi menunjukkan efisiensi 95% bulan ini.',
      tipEN: 'In Batam factories, "report" often refers to the daily production summary sent to Singapore HQ.',
      tipID: 'Di pabrik Batam, "report" sering merujuk pada ringkasan produksi harian yang dikirim ke kantor pusat Singapura.',
    },
    {
      id: 'deadline',
      week: 4,
      word: 'DEADLINE',
      phonetic: '/ˈded.laɪn/',
      meaningID: 'Tenggat Waktu / Batas Waktu',
      meaningEN: 'The latest time by which something must be finished',
      sentenceEN: 'The deadline for this project is next Wednesday.',
      sentenceID: 'Tenggat waktu proyek ini adalah Rabu depan.',
      sentenceEN2: 'We must meet the deadline or the client will be unhappy.',
      sentenceID2: 'Kita harus memenuhi tenggat waktu atau klien akan kecewa.',
      tipEN: 'Never miss a deadline with Singapore clients — punctuality is extremely valued.',
      tipID: 'Jangan pernah melewati tenggat waktu dengan klien Singapura — ketepatan waktu sangat dihargai.',
    },
    {
      id: 'confirm',
      week: 1,
      word: 'CONFIRM',
      phonetic: '/kənˈfɜːm/',
      meaningID: 'Mengonfirmasi / Memastikan',
      meaningEN: 'To state or show that something is definitely true or correct',
      sentenceEN: 'Please confirm your attendance by tomorrow.',
      sentenceID: 'Tolong konfirmasi kehadiran Anda sebelum besok.',
      sentenceEN2: 'Can you confirm the order has been shipped?',
      sentenceID2: 'Bisakah Anda konfirmasi bahwa pesanan sudah dikirim?',
      tipEN: 'Always confirm meeting times in writing when working with overseas partners.',
      tipID: 'Selalu konfirmasi waktu rapat secara tertulis saat bekerja dengan mitra luar negeri.',
    },
    {
      id: 'update',
      week: 3,
      word: 'UPDATE',
      phonetic: '/ˈʌp.deɪt/',
      meaningID: 'Pembaruan / Memperbarui',
      meaningEN: 'The latest information about something; to give the newest information',
      sentenceEN: 'Can you give me an update on the shipment status?',
      sentenceID: 'Bisakah Anda memberi saya pembaruan tentang status pengiriman?',
      sentenceEN2: 'I will update you as soon as I hear back from the supplier.',
      sentenceID2: 'Saya akan memperbarui Anda segera setelah saya mendapat kabar dari pemasok.',
      tipEN: '"Give me an update" is a phrase you will hear constantly in Batam–Singapore operations.',
      tipID: '"Give me an update" adalah frasa yang sering terdengar dalam operasi Batam–Singapura.',
    },
    {
      id: 'approve',
      week: 3,
      word: 'APPROVE',
      phonetic: '/əˈpruːv/',
      meaningID: 'Menyetujui / Memberikan Persetujuan',
      meaningEN: 'To officially agree to something or say it is acceptable',
      sentenceEN: 'The manager needs to approve this purchase order.',
      sentenceID: 'Manajer perlu menyetujui pesanan pembelian ini.',
      sentenceEN2: 'My boss approved the budget for the new equipment.',
      sentenceID2: 'Atasan saya menyetujui anggaran untuk peralatan baru.',
      tipEN: 'In formal settings, always ask "Has this been approved?" before proceeding.',
      tipID: 'Dalam situasi formal, selalu tanyakan "Has this been approved?" sebelum melanjutkan.',
    },
    {
      id: 'client',
      week: 2,
      word: 'CLIENT',
      phonetic: '/ˈklaɪ.ənt/',
      meaningID: 'Klien / Pelanggan Bisnis',
      meaningEN: 'A person or company that pays for services or products',
      sentenceEN: 'Our biggest client is based in Singapore.',
      sentenceID: 'Klien terbesar kami berbasis di Singapura.',
      sentenceEN2: 'We need to deliver quality results to keep the client happy.',
      sentenceID2: 'Kita perlu menghasilkan kualitas terbaik agar klien puas.',
      tipEN: 'Use "client" for business relationships and "customer" for retail or walk-in buyers.',
      tipID: 'Gunakan "client" untuk hubungan bisnis dan "customer" untuk pembeli ritel atau langsung.',
    },
    {
      id: 'invoice',
      week: 8,
      word: 'INVOICE',
      phonetic: '/ˈɪn.vɔɪs/',
      meaningID: 'Faktur / Tagihan',
      meaningEN: 'A bill listing goods or services provided and the amount owed',
      sentenceEN: 'Please send the invoice to our accounts team.',
      sentenceID: 'Tolong kirim faktur ke tim akuntansi kami.',
      sentenceEN2: 'The invoice must be paid within 30 days.',
      sentenceID2: 'Faktur harus dibayar dalam 30 hari.',
      tipEN: 'Invoices between Batam FTZ companies and Singapore often use USD or SGD.',
      tipID: 'Faktur antara perusahaan di FTZ Batam dan Singapura sering menggunakan USD atau SGD.',
    },
    {
      id: 'contract',
      week: 7,
      word: 'CONTRACT',
      phonetic: '/ˈkɒn.trækt/',
      meaningID: 'Kontrak / Perjanjian Tertulis',
      meaningEN: 'A formal legal agreement between two or more parties',
      sentenceEN: 'We signed the contract with the new supplier yesterday.',
      sentenceID: 'Kami menandatangani kontrak dengan pemasok baru kemarin.',
      sentenceEN2: 'The contract includes payment terms and delivery dates.',
      sentenceID2: 'Kontrak tersebut mencakup syarat pembayaran dan tanggal pengiriman.',
      tipEN: 'Always read a contract carefully before signing, especially international ones.',
      tipID: 'Selalu baca kontrak dengan cermat sebelum menandatangani, terutama yang internasional.',
    },
    {
      id: 'shipment',
      week: 17,
      word: 'SHIPMENT',
      phonetic: '/ˈʃɪp.mənt/',
      meaningID: 'Pengiriman / Muatan',
      meaningEN: 'A quantity of goods sent together at one time',
      sentenceEN: 'The shipment from Singapore arrived this morning.',
      sentenceID: 'Kiriman dari Singapura tiba pagi ini.',
      sentenceEN2: 'We need to track the shipment before it reaches customs.',
      sentenceID2: 'Kita perlu melacak pengiriman sebelum sampai ke bea cukai.',
      tipEN: 'Batam\'s FTZ status means many shipments have special customs procedures.',
      tipID: 'Status FTZ Batam berarti banyak kiriman memiliki prosedur bea cukai khusus.',
    },
    {
      id: 'present',
      week: 6,
      word: 'PRESENT',
      phonetic: '/prɪˈzent/',
      meaningID: 'Mempresentasikan / Menyajikan',
      meaningEN: 'To show or explain something formally to an audience',
      sentenceEN: 'She will present the sales results to the board tomorrow.',
      sentenceID: 'Dia akan mempresentasikan hasil penjualan kepada dewan besok.',
      sentenceEN2: 'I am nervous about presenting in English for the first time.',
      sentenceID2: 'Saya gugup untuk mempresentasikan dalam bahasa Inggris untuk pertama kalinya.',
      tipEN: 'Practice your opening line: "Good morning, I am here to present..."',
      tipID: 'Latih kalimat pembuka Anda: "Good morning, I am here to present..."',
    },
    {
      id: 'feedback',
      week: 10,
      word: 'FEEDBACK',
      phonetic: '/ˈfiːd.bæk/',
      meaningID: 'Masukan / Umpan Balik',
      meaningEN: 'Information about performance used to improve future results',
      sentenceEN: 'The manager gave us useful feedback after the presentation.',
      sentenceID: 'Manajer memberikan masukan berguna setelah presentasi.',
      sentenceEN2: 'Please share your feedback so we can improve the product.',
      sentenceID2: 'Tolong bagikan masukan Anda agar kami dapat meningkatkan produk.',
      tipEN: 'In professional English, "feedback" is neutral — not automatically negative.',
      tipID: 'Dalam bahasa Inggris profesional, "feedback" bersifat netral — tidak otomatis negatif.',
    },
    {
      id: 'target',
      week: 11,
      word: 'TARGET',
      phonetic: '/ˈtɑː.ɡɪt/',
      meaningID: 'Target / Sasaran',
      meaningEN: 'A goal or result that you aim to achieve',
      sentenceEN: 'Our sales target for this quarter is 500 units.',
      sentenceID: 'Target penjualan kami untuk kuartal ini adalah 500 unit.',
      sentenceEN2: 'We met our production target two days early.',
      sentenceID2: 'Kami mencapai target produksi dua hari lebih awal.',
      tipEN: '"On target" means progressing as planned. "Off target" means falling behind.',
      tipID: '"On target" artinya berjalan sesuai rencana. "Off target" berarti tertinggal.',
    },
    {
      id: 'urgent',
      week: 4,
      word: 'URGENT',
      phonetic: '/ˈɜː.dʒənt/',
      meaningID: 'Mendesak / Segera',
      meaningEN: 'Requiring immediate attention or action',
      sentenceEN: 'This is urgent — please reply as soon as possible.',
      sentenceID: 'Ini mendesak — tolong balas sesegera mungkin.',
      sentenceEN2: 'We have an urgent request from the Singapore office.',
      sentenceID2: 'Kami mendapat permintaan mendesak dari kantor Singapura.',
      tipEN: 'Reserve "urgent" for genuinely critical matters — overusing it loses its impact.',
      tipID: 'Simpan kata "urgent" untuk hal yang benar-benar kritis — penggunaan berlebihan mengurangi dampaknya.',
    },
    {
      id: 'attend',
      week: 3,
      word: 'ATTEND',
      phonetic: '/əˈtend/',
      meaningID: 'Menghadiri / Hadir',
      meaningEN: 'To be present at an event or meeting',
      sentenceEN: 'All managers are required to attend the quarterly review.',
      sentenceID: 'Semua manajer diwajibkan hadir di tinjauan kuartalan.',
      sentenceEN2: 'Will you attend the trade fair in Singapore next month?',
      sentenceID2: 'Apakah Anda akan menghadiri pameran dagang di Singapura bulan depan?',
      tipEN: '"Attend" is more formal than "come to" — use it in official written communication.',
      tipID: '"Attend" lebih formal dari "come to" — gunakan dalam komunikasi tertulis resmi.',
    },
    {
      id: 'colleague',
      week: 1,
      word: 'COLLEAGUE',
      phonetic: '/ˈkɒl.iːɡ/',
      meaningID: 'Rekan Kerja / Kolega',
      meaningEN: 'A person you work with in the same organisation',
      sentenceEN: 'My colleague will handle your enquiry while I am away.',
      sentenceID: 'Rekan kerja saya akan menangani pertanyaan Anda saat saya tidak ada.',
      sentenceEN2: 'I would like to introduce my colleague from the operations team.',
      sentenceID2: 'Saya ingin memperkenalkan rekan saya dari tim operasional.',
      tipEN: 'Use "colleague" rather than "friend" in professional English introductions.',
      tipID: 'Gunakan "colleague" daripada "friend" dalam perkenalan bahasa Inggris profesional.',
    },
    {
      id: 'department',
      week: 10,
      word: 'DEPARTMENT',
      phonetic: '/dɪˈpɑːt.mənt/',
      meaningID: 'Departemen / Divisi',
      meaningEN: 'A section of a company responsible for a specific function',
      sentenceEN: 'Please contact the HR department for your onboarding documents.',
      sentenceID: 'Silakan hubungi departemen HR untuk dokumen orientasi Anda.',
      sentenceEN2: 'The finance department approved the new budget last week.',
      sentenceID2: 'Departemen keuangan menyetujui anggaran baru minggu lalu.',
      tipEN: 'Common Batam departments: Production, QC, Logistics, HR, Finance, Sales, Export.',
      tipID: 'Departemen umum di Batam: Produksi, QC, Logistik, SDM, Keuangan, Penjualan, Ekspor.',
    },
    {
      id: 'order',
      week: 9,
      word: 'ORDER',
      phonetic: '/ˈɔː.dər/',
      meaningID: 'Pesanan / Memesan',
      meaningEN: 'A request to supply goods or services; to make such a request',
      sentenceEN: 'We received a large order from our Singapore distributor.',
      sentenceID: 'Kami menerima pesanan besar dari distributor Singapura kami.',
      sentenceEN2: 'The customer wants to order 200 units for delivery next month.',
      sentenceID2: 'Pelanggan ingin memesan 200 unit untuk pengiriman bulan depan.',
      tipEN: 'In B2B English: "place an order" (not "make an order") is the correct phrase.',
      tipID: 'Dalam bahasa Inggris B2B: "place an order" (bukan "make an order") adalah frasa yang benar.',
    },
    {
      id: 'respond',
      week: 2,
      word: 'RESPOND',
      phonetic: '/rɪˈspɒnd/',
      meaningID: 'Merespons / Membalas',
      meaningEN: 'To reply or react to something',
      sentenceEN: 'Please respond to the client\'s email within 24 hours.',
      sentenceID: 'Tolong balas email klien dalam 24 jam.',
      sentenceEN2: 'I will respond to all enquiries before the end of the week.',
      sentenceID2: 'Saya akan merespons semua pertanyaan sebelum akhir minggu.',
      tipEN: '"Respond" is more formal than "reply" and is preferred in written business English.',
      tipID: '"Respond" lebih formal dari "reply" dan lebih disukai dalam bahasa Inggris bisnis tertulis.',
    },
    {
      id: 'arrange',
      week: 4,
      word: 'ARRANGE',
      phonetic: '/əˈreɪndʒ/',
      meaningID: 'Mengatur / Menyelenggarakan',
      meaningEN: 'To plan or organize something in advance',
      sentenceEN: 'Can you arrange a car to pick up the visitors from the ferry terminal?',
      sentenceID: 'Bisakah Anda mengatur mobil untuk menjemput tamu dari terminal feri?',
      sentenceEN2: 'I will arrange the conference room for the afternoon session.',
      sentenceID2: 'Saya akan mengatur ruang konferensi untuk sesi sore.',
      tipEN: 'Batam tip: always arrange transportation for Singapore visitors arriving by ferry.',
      tipID: 'Tips Batam: selalu atur transportasi untuk tamu Singapura yang tiba dengan feri.',
    },
    {
      id: 'quality',
      week: 17,
      word: 'QUALITY',
      phonetic: '/ˈkwɒl.ɪ.ti/',
      meaningID: 'Kualitas / Mutu',
      meaningEN: 'The standard of something, often measured against others of a similar kind',
      sentenceEN: 'We never compromise on the quality of our products.',
      sentenceID: 'Kami tidak pernah berkompromi terhadap kualitas produk kami.',
      sentenceEN2: 'Quality control is a top priority at our Batam facility.',
      sentenceID2: 'Pengendalian kualitas adalah prioritas utama di fasilitas Batam kami.',
      tipEN: '"Quality assurance" (QA) and "quality control" (QC) are key terms in Batam manufacturing.',
      tipID: '"Quality assurance" (QA) dan "quality control" (QC) adalah istilah kunci dalam manufaktur Batam.',
    },
    {
      id: 'support',
      week: 9,
      word: 'SUPPORT',
      phonetic: '/səˈpɔːt/',
      meaningID: 'Dukungan / Mendukung',
      meaningEN: 'Help given to someone; to give help or assistance',
      sentenceEN: 'Our technical support team is available 24 hours a day.',
      sentenceID: 'Tim dukungan teknis kami tersedia 24 jam sehari.',
      sentenceEN2: 'Thank you for your support during this difficult project.',
      sentenceID2: 'Terima kasih atas dukungan Anda selama proyek yang sulit ini.',
      tipEN: '"Customer support" and "after-sales support" are essential phrases in service industries.',
      tipID: '"Customer support" dan "after-sales support" adalah frasa penting di industri jasa.',
    },
    {
      id: 'budget',
      week: 16,
      word: 'BUDGET',
      phonetic: '/ˈbʌdʒ.ɪt/',
      meaningID: 'Anggaran',
      meaningEN: 'A plan for how money will be spent over a period of time',
      sentenceEN: 'We need to stay within the project budget.',
      sentenceID: 'Kita perlu tetap dalam anggaran proyek.',
      sentenceEN2: 'The annual budget meeting is scheduled for next month.',
      sentenceID2: 'Rapat anggaran tahunan dijadwalkan bulan depan.',
      tipEN: '"Over budget" means spending too much. "Under budget" means spending less than planned — which is good.',
      tipID: '"Over budget" berarti pengeluaran terlalu banyak. "Under budget" berarti pengeluaran lebih sedikit dari rencana — yang artinya bagus.',
    },
    {
      id: 'hire',
      week: 18,
      word: 'HIRE',
      phonetic: '/haɪər/',
      meaningID: 'Merekrut / Mempekerjakan',
      meaningEN: 'To employ someone for payment',
      sentenceEN: 'We are looking to hire three new engineers this quarter.',
      sentenceID: 'Kami berencana merekrut tiga insinyur baru kuartal ini.',
      sentenceEN2: 'The HR team will hire a local coordinator for the Singapore project.',
      sentenceID2: 'Tim HR akan mempekerjakan koordinator lokal untuk proyek Singapura.',
      tipEN: 'In formal HR, use "recruit" or "onboard" — "hire" is slightly more casual.',
      tipID: 'Dalam HR formal, gunakan "recruit" atau "onboard" — "hire" sedikit lebih santai.',
    },
    {
      id: 'available',
      week: 5,
      word: 'AVAILABLE',
      phonetic: '/əˈveɪ.lə.bəl/',
      meaningID: 'Tersedia / Bisa Ditemui',
      meaningEN: 'Free to be used, seen, or reached; not busy',
      sentenceEN: 'Are you available for a call at 3 PM today?',
      sentenceID: 'Apakah Anda tersedia untuk panggilan pukul 3 sore hari ini?',
      sentenceEN2: 'The manager is not available right now — she is in a meeting.',
      sentenceID2: 'Manajer tidak tersedia sekarang — dia sedang dalam rapat.',
      tipEN: 'This is one of the most common phrases in business English scheduling.',
      tipID: 'Ini adalah salah satu frasa paling umum dalam penjadwalan bahasa Inggris bisnis.',
    },
    {
      id: 'issue',
      week: 14,
      word: 'ISSUE',
      phonetic: '/ˈɪʃ.uː/',
      meaningID: 'Masalah / Isu',
      meaningEN: 'A problem or important topic that needs to be discussed or resolved',
      sentenceEN: 'We have an issue with the latest batch of components.',
      sentenceID: 'Kami memiliki masalah dengan batch komponen terbaru.',
      sentenceEN2: 'Please raise any issues before the end of the meeting.',
      sentenceID2: 'Tolong sampaikan setiap masalah sebelum rapat berakhir.',
      tipEN: '"Issue" is softer than "problem" — it is preferred in professional communication.',
      tipID: '"Issue" lebih halus dari "problem" — lebih disukai dalam komunikasi profesional.',
    },
    {
      id: 'progress',
      week: 11,
      word: 'PROGRESS',
      phonetic: '/ˈprəʊ.ɡres/',
      meaningID: 'Kemajuan / Perkembangan',
      meaningEN: 'Movement forward towards a goal or better state',
      sentenceEN: 'Can you give me a progress report on the construction project?',
      sentenceID: 'Bisakah Anda memberi saya laporan kemajuan proyek konstruksi?',
      sentenceEN2: 'We are making good progress on the new product line.',
      sentenceID2: 'Kami membuat kemajuan yang baik pada lini produk baru.',
      tipEN: '"In progress" means something is currently being worked on.',
      tipID: '"In progress" berarti sesuatu sedang dikerjakan saat ini.',
    },
    {
      id: 'proposal',
      week: 6,
      word: 'PROPOSAL',
      phonetic: '/prəˈpəʊ.zəl/',
      meaningID: 'Proposal / Usulan',
      meaningEN: 'A formal written plan or suggestion for consideration',
      sentenceEN: 'We submitted a proposal to the Singapore government agency.',
      sentenceID: 'Kami mengajukan proposal ke lembaga pemerintah Singapura.',
      sentenceEN2: 'Please review the proposal before our meeting tomorrow.',
      sentenceID2: 'Tolong tinjau proposal sebelum rapat kita besok.',
      tipEN: 'A strong proposal has: executive summary, problem, solution, timeline, and cost.',
      tipID: 'Proposal yang kuat memiliki: ringkasan eksekutif, masalah, solusi, timeline, dan biaya.',
    },
  ],

  medium: [
    {
      id: 'negotiate',
      week: 7,
      word: 'NEGOTIATE',
      phonetic: '/nɪˈɡoʊ.ʃi.eɪt/',
      meaningID: 'Bernegosiasi / Merundingkan',
      meaningEN: 'To discuss terms with another party in order to reach an agreement',
      sentenceEN: 'We need to negotiate the pricing before we sign the contract.',
      sentenceID: 'Kita perlu bernegosiasi soal harga sebelum menandatangani kontrak.',
      sentenceEN2: 'She successfully negotiated a 15% discount with the supplier.',
      sentenceID2: 'Dia berhasil menegosiasikan diskon 15% dengan pemasok.',
      tipEN: 'In Batam FTZ, English negotiation skills directly impact deal quality with Singapore partners.',
      tipID: 'Di FTZ Batam, kemampuan negosiasi bahasa Inggris langsung mempengaruhi kualitas kesepakatan dengan mitra Singapura.',
    },
    {
      id: 'collaborate',
      week: 12,
      word: 'COLLABORATE',
      phonetic: '/kəˈlæb.ə.reɪt/',
      meaningID: 'Berkolaborasi / Bekerja Sama',
      meaningEN: 'To work jointly with others to achieve a common goal',
      sentenceEN: 'Our Batam and Singapore teams collaborate on every major project.',
      sentenceID: 'Tim Batam dan Singapura kami berkolaborasi dalam setiap proyek besar.',
      sentenceEN2: 'We collaborate with three international partners on this initiative.',
      sentenceID2: 'Kami berkolaborasi dengan tiga mitra internasional dalam inisiatif ini.',
      tipEN: '"Collaborate" implies equal contribution — stronger than "cooperate" or "work with".',
      tipID: '"Collaborate" menyiratkan kontribusi yang setara — lebih kuat dari "cooperate" atau "work with".',
    },
    {
      id: 'delegate',
      week: 10,
      word: 'DELEGATE',
      phonetic: '/ˈdel.ɪ.ɡeɪt/',
      meaningID: 'Mendelegasikan / Melimpahkan Tugas',
      meaningEN: 'To assign responsibility or authority to someone else',
      sentenceEN: 'A good manager knows when to delegate tasks to the team.',
      sentenceID: 'Manajer yang baik tahu kapan mendelegasikan tugas kepada tim.',
      sentenceEN2: 'I will delegate the logistics coordination to my senior officer.',
      sentenceID2: 'Saya akan mendelegasikan koordinasi logistik kepada petugas senior saya.',
      tipEN: 'Delegation is a leadership skill — not a sign of weakness. Use it confidently.',
      tipID: 'Delegasi adalah keterampilan kepemimpinan — bukan tanda kelemahan. Gunakan dengan percaya diri.',
    },
    {
      id: 'facilitate',
      week: 3,
      word: 'FACILITATE',
      phonetic: '/fəˈsɪl.ɪ.teɪt/',
      meaningID: 'Memfasilitasi / Mempermudah',
      meaningEN: 'To make a process or action easier or more straightforward',
      sentenceEN: 'The HR team will facilitate the onboarding of new international staff.',
      sentenceID: 'Tim HR akan memfasilitasi orientasi staf internasional baru.',
      sentenceEN2: 'She was asked to facilitate the cross-departmental meeting.',
      sentenceID2: 'Dia diminta untuk memfasilitasi rapat lintas departemen.',
      tipEN: '"Facilitate" is preferred over "help run" in formal business English.',
      tipID: '"Facilitate" lebih disukai daripada "help run" dalam bahasa Inggris bisnis formal.',
    },
    {
      id: 'clarify',
      week: 7,
      word: 'CLARIFY',
      phonetic: '/ˈklær.ɪ.faɪ/',
      meaningID: 'Mengklarifikasi / Memperjelas',
      meaningEN: 'To make something clearer and easier to understand',
      sentenceEN: 'Could you clarify what you mean by the revised timeline?',
      sentenceID: 'Bisakah Anda mengklarifikasi apa yang Anda maksud dengan timeline yang direvisi?',
      sentenceEN2: 'Let me clarify our position on the delivery terms.',
      sentenceID2: 'Izinkan saya mengklarifikasi posisi kami mengenai syarat pengiriman.',
      tipEN: '"Could you clarify...?" is a polite, non-confrontational way to ask for more detail.',
      tipID: '"Could you clarify...?" adalah cara sopan dan tidak konfrontatif untuk meminta detail lebih lanjut.',
    },
    {
      id: 'implement',
      week: 11,
      word: 'IMPLEMENT',
      phonetic: '/ˈɪm.plɪ.ment/',
      meaningID: 'Mengimplementasikan / Menerapkan',
      meaningEN: 'To put a plan, decision, or system into effect',
      sentenceEN: 'We will implement the new quality system starting next quarter.',
      sentenceID: 'Kami akan menerapkan sistem kualitas baru mulai kuartal depan.',
      sentenceEN2: 'The board approved the plan — now we need to implement it.',
      sentenceID2: 'Dewan menyetujui rencana — sekarang kita perlu menerapkannya.',
      tipEN: '"Implementation" is the phase after planning — it means putting the plan into action.',
      tipID: '"Implementation" adalah fase setelah perencanaan — artinya menjalankan rencana tersebut.',
    },
    {
      id: 'escalate',
      week: 14,
      word: 'ESCALATE',
      phonetic: '/ˈes.kə.leɪt/',
      meaningID: 'Meningkatkan / Membawa ke Tingkat Lebih Tinggi',
      meaningEN: 'To raise an issue to a higher authority or make it more serious',
      sentenceEN: 'If the issue is not resolved today, I will escalate it to the director.',
      sentenceID: 'Jika masalah tidak diselesaikan hari ini, saya akan membawanya ke direktur.',
      sentenceEN2: 'Do not escalate the problem without trying to solve it first.',
      sentenceID2: 'Jangan eskalasi masalah tanpa mencoba menyelesaikannya terlebih dahulu.',
      tipEN: 'Knowing when to escalate — and when not to — is a core professional competency.',
      tipID: 'Mengetahui kapan harus eskalasi — dan kapan tidak — adalah kompetensi profesional utama.',
    },
    {
      id: 'prioritise',
      week: 4,
      word: 'PRIORITISE',
      phonetic: '/praɪˈɒr.ɪ.taɪz/',
      meaningID: 'Memprioritaskan',
      meaningEN: 'To decide the order in which tasks should be done based on importance',
      sentenceEN: 'We need to prioritise the client requests that have the shortest deadlines.',
      sentenceID: 'Kita perlu memprioritaskan permintaan klien yang memiliki tenggat waktu tersingkat.',
      sentenceEN2: 'Please prioritise quality over speed on this particular order.',
      sentenceID2: 'Tolong prioritaskan kualitas daripada kecepatan untuk pesanan ini.',
      tipEN: 'American spelling: "prioritize" — both are acceptable in international business.',
      tipID: 'Ejaan Amerika: "prioritize" — keduanya dapat diterima dalam bisnis internasional.',
    },
    {
      id: 'stakeholder',
      week: 20,
      word: 'STAKEHOLDER',
      phonetic: '/ˈsteɪk.həʊl.dər/',
      meaningID: 'Pemangku Kepentingan',
      meaningEN: 'A person or group with an interest in the success of a project or organisation',
      sentenceEN: 'All key stakeholders must be informed before we announce the decision.',
      sentenceID: 'Semua pemangku kepentingan utama harus diberitahu sebelum kami mengumumkan keputusan.',
      sentenceEN2: 'Stakeholder management is critical in any large infrastructure project.',
      sentenceID2: 'Manajemen pemangku kepentingan sangat penting dalam proyek infrastruktur besar.',
      tipEN: 'In Batam joint ventures, stakeholders include local government, Singapore partners, and investors.',
      tipID: 'Dalam usaha patungan di Batam, pemangku kepentingan mencakup pemerintah daerah, mitra Singapura, dan investor.',
    },
    {
      id: 'benchmark',
      week: 20,
      word: 'BENCHMARK',
      phonetic: '/ˈbentʃ.mɑːk/',
      meaningID: 'Tolok Ukur / Patokan',
      meaningEN: 'A standard used to measure or compare performance',
      sentenceEN: 'Our production efficiency is now above the industry benchmark.',
      sentenceID: 'Efisiensi produksi kami kini berada di atas tolok ukur industri.',
      sentenceEN2: 'We use Singapore\'s manufacturing standards as our benchmark.',
      sentenceID2: 'Kami menggunakan standar manufaktur Singapura sebagai tolok ukur kami.',
      tipEN: '"Set a benchmark" means to establish a standard. "Meet the benchmark" means to achieve it.',
      tipID: '"Set a benchmark" berarti menetapkan standar. "Meet the benchmark" berarti mencapainya.',
    },
    {
      id: 'initiative',
      week: 21,
      word: 'INITIATIVE',
      phonetic: '/ɪˈnɪʃ.ə.tɪv/',
      meaningID: 'Inisiatif / Prakarsa',
      meaningEN: 'A new plan or action designed to solve a problem or achieve a goal',
      sentenceEN: 'The company launched an initiative to reduce production waste by 30%.',
      sentenceID: 'Perusahaan meluncurkan inisiatif untuk mengurangi limbah produksi sebesar 30%.',
      sentenceEN2: 'I appreciate employees who take initiative without being asked.',
      sentenceID2: 'Saya menghargai karyawan yang berinisiatif tanpa harus diminta.',
      tipEN: '"Take the initiative" is a strong phrase — it shows leadership and proactivity.',
      tipID: '"Take the initiative" adalah frasa yang kuat — menunjukkan kepemimpinan dan proaktivitas.',
    },
    {
      id: 'comply',
      week: 18,
      word: 'COMPLY',
      phonetic: '/kəmˈplaɪ/',
      meaningID: 'Mematuhi / Memenuhi Persyaratan',
      meaningEN: 'To act in accordance with rules, standards, or instructions',
      sentenceEN: 'All vendors must comply with our ISO quality standards.',
      sentenceID: 'Semua vendor harus mematuhi standar kualitas ISO kami.',
      sentenceEN2: 'The factory was audited to ensure it complied with environmental regulations.',
      sentenceID2: 'Pabrik diaudit untuk memastikan kepatuhannya terhadap peraturan lingkungan.',
      tipEN: '"Comply with" is always followed by a standard, rule, or requirement.',
      tipID: '"Comply with" selalu diikuti dengan standar, aturan, atau persyaratan.',
    },
    {
      id: 'evaluate',
      week: 13,
      word: 'EVALUATE',
      phonetic: '/ɪˈvæl.ju.eɪt/',
      meaningID: 'Mengevaluasi / Menilai',
      meaningEN: 'To carefully assess and judge the quality or value of something',
      sentenceEN: 'We will evaluate all supplier proposals before making a decision.',
      sentenceID: 'Kami akan mengevaluasi semua proposal pemasok sebelum membuat keputusan.',
      sentenceEN2: 'The manager evaluated each team member\'s performance last quarter.',
      sentenceID2: 'Manajer mengevaluasi kinerja setiap anggota tim kuartal lalu.',
      tipEN: 'In performance reviews, "evaluate" is a key verb — practice using it naturally.',
      tipID: 'Dalam evaluasi kinerja, "evaluate" adalah kata kerja kunci — latih penggunaannya secara alami.',
    },
    {
      id: 'comprehensive',
      week: 8,
      word: 'COMPREHENSIVE',
      phonetic: '/ˌkɒm.prɪˈhen.sɪv/',
      meaningID: 'Komprehensif / Menyeluruh',
      meaningEN: 'Including all or nearly all aspects of something; thorough',
      sentenceEN: 'Please prepare a comprehensive report on the Q3 results.',
      sentenceID: 'Tolong buat laporan komprehensif tentang hasil Q3.',
      sentenceEN2: 'We conducted a comprehensive review of all vendor contracts.',
      sentenceID2: 'Kami melakukan tinjauan menyeluruh terhadap semua kontrak vendor.',
      tipEN: '"Comprehensive" signals thoroughness — use it to describe reports, plans, and reviews.',
      tipID: '"Comprehensive" menandakan ketuntasan — gunakan untuk mendeskripsikan laporan, rencana, dan tinjauan.',
    },
    {
      id: 'transparency',
      week: 10,
      word: 'TRANSPARENCY',
      phonetic: '/trænsˈpær.ən.si/',
      meaningID: 'Transparansi / Keterbukaan',
      meaningEN: 'The quality of being open, honest, and free from hidden agendas',
      sentenceEN: 'We believe in full transparency with our investors and partners.',
      sentenceID: 'Kami percaya pada transparansi penuh dengan investor dan mitra kami.',
      sentenceEN2: 'Transparency in reporting builds long-term trust with Singapore clients.',
      sentenceID2: 'Transparansi dalam pelaporan membangun kepercayaan jangka panjang dengan klien Singapura.',
      tipEN: 'Transparency is increasingly valued in international business — especially post-COVID supply chains.',
      tipID: 'Transparansi semakin dihargai dalam bisnis internasional — terutama rantai pasokan pasca-COVID.',
    },
    {
      id: 'restructure',
      week: 22,
      word: 'RESTRUCTURE',
      phonetic: '/ˌriːˈstrʌk.tʃər/',
      meaningID: 'Merestrukturisasi / Menata Ulang',
      meaningEN: 'To reorganise the way something is organised or operated',
      sentenceEN: 'The company plans to restructure its operations after the merger.',
      sentenceID: 'Perusahaan berencana merestrukturisasi operasinya setelah merger.',
      sentenceEN2: 'We restructured the supply chain to reduce dependence on a single vendor.',
      sentenceID2: 'Kami merestrukturisasi rantai pasokan untuk mengurangi ketergantungan pada satu vendor.',
      tipEN: 'Restructuring can be positive or negative — context determines the tone.',
      tipID: 'Restrukturisasi bisa positif atau negatif — konteks menentukan nadanya.',
    },
    {
      id: 'contingency',
      week: 22,
      word: 'CONTINGENCY',
      phonetic: '/kənˈtɪn.dʒən.si/',
      meaningID: 'Kontingensi / Rencana Cadangan',
      meaningEN: 'A provision made for an unexpected event or emergency situation',
      sentenceEN: 'We always have a contingency plan in case production is disrupted.',
      sentenceID: 'Kami selalu memiliki rencana kontingensi jika produksi terganggu.',
      sentenceEN2: 'The project manager set aside 10% of the budget as a contingency fund.',
      sentenceID2: 'Manajer proyek menyisihkan 10% anggaran sebagai dana kontingensi.',
      tipEN: '"Contingency plan" = Plan B. Always have one in Batam\'s fast-moving industrial environment.',
      tipID: '"Contingency plan" = Rencana B. Selalu miliki satu dalam lingkungan industri Batam yang bergerak cepat.',
    },
    {
      id: 'consensus',
      week: 3,
      word: 'CONSENSUS',
      phonetic: '/kənˈsen.səs/',
      meaningID: 'Konsensus / Kesepakatan Bersama',
      meaningEN: 'A general agreement among a group of people',
      sentenceEN: 'We reached a consensus on the new workplace safety policy.',
      sentenceID: 'Kami mencapai konsensus tentang kebijakan keselamatan kerja baru.',
      sentenceEN2: 'Is there a consensus on which supplier we should choose?',
      sentenceID2: 'Apakah ada konsensus tentang pemasok mana yang harus kita pilih?',
      tipEN: '"By consensus" means everyone agreed — useful in meeting minutes and decisions.',
      tipID: '"By consensus" berarti semua setuju — berguna dalam notulen rapat dan keputusan.',
    },
    {
      id: 'accountability',
      week: 10,
      word: 'ACCOUNTABILITY',
      phonetic: '/əˌkaʊn.təˈbɪl.ɪ.ti/',
      meaningID: 'Akuntabilitas / Tanggung Jawab',
      meaningEN: 'The responsibility to report on and be answerable for one\'s actions',
      sentenceEN: 'Strong accountability culture is what sets top-performing teams apart.',
      sentenceID: 'Budaya akuntabilitas yang kuat adalah yang membedakan tim berprestasi tinggi.',
      sentenceEN2: 'Each department head has full accountability for their budget spending.',
      sentenceID2: 'Setiap kepala departemen bertanggung jawab penuh atas pengeluaran anggaran mereka.',
      tipEN: 'In meetings, using "accountability" shows professional maturity and leadership readiness.',
      tipID: 'Dalam rapat, menggunakan "accountability" menunjukkan kematangan profesional dan kesiapan kepemimpinan.',
    },
    {
      id: 'streamline',
      week: 17,
      word: 'STREAMLINE',
      phonetic: '/ˈstriːm.laɪn/',
      meaningID: 'Menyederhanakan / Mengefisienkan',
      meaningEN: 'To make a process simpler and more efficient',
      sentenceEN: 'We are streamlining the approval process to save time.',
      sentenceID: 'Kami menyederhanakan proses persetujuan untuk menghemat waktu.',
      sentenceEN2: 'The new software will streamline our export documentation.',
      sentenceID2: 'Perangkat lunak baru akan mengefisienkan dokumentasi ekspor kami.',
      tipEN: '"Streamline" is a favourite word in operations and process improvement discussions.',
      tipID: '"Streamline" adalah kata favorit dalam diskusi operasional dan peningkatan proses.',
    },
    {
      id: 'procurement',
      week: 17,
      word: 'PROCUREMENT',
      phonetic: '/prəˈkjʊər.mənt/',
      meaningID: 'Pengadaan / Pembelian',
      meaningEN: 'The process of obtaining goods and services for business use',
      sentenceEN: 'Our procurement team handles all vendor sourcing and purchasing.',
      sentenceID: 'Tim pengadaan kami menangani semua pencarian vendor dan pembelian.',
      sentenceEN2: 'Efficient procurement reduces costs significantly in manufacturing.',
      sentenceID2: 'Pengadaan yang efisien mengurangi biaya secara signifikan dalam manufaktur.',
      tipEN: 'In Batam factories, procurement involves both local suppliers and Singapore/Malaysia vendors.',
      tipID: 'Di pabrik Batam, pengadaan melibatkan pemasok lokal dan vendor dari Singapura/Malaysia.',
    },
    {
      id: 'sustainable',
      week: 21,
      word: 'SUSTAINABLE',
      phonetic: '/səˈsteɪ.nə.bəl/',
      meaningID: 'Berkelanjutan / Ramah Lingkungan Jangka Panjang',
      meaningEN: 'Able to continue over a long period without damaging the environment or depleting resources',
      sentenceEN: 'Our company is committed to sustainable manufacturing practices.',
      sentenceID: 'Perusahaan kami berkomitmen pada praktik manufaktur yang berkelanjutan.',
      sentenceEN2: 'Singapore clients increasingly require sustainable supply chain certification.',
      sentenceID2: 'Klien Singapura semakin membutuhkan sertifikasi rantai pasokan yang berkelanjutan.',
      tipEN: 'ESG (Environmental, Social, Governance) and sustainability are hot topics in Singapore business.',
      tipID: 'ESG (Lingkungan, Sosial, Tata Kelola) dan keberlanjutan adalah topik hangat dalam bisnis Singapura.',
    },
    {
      id: 'arbitration',
      week: 19,
      word: 'ARBITRATION',
      phonetic: '/ˌɑː.bɪˈtreɪ.ʃən/',
      meaningID: 'Arbitrase / Penyelesaian Sengketa',
      meaningEN: 'A method of resolving disputes outside of court, using a neutral third party',
      sentenceEN: 'The contract includes an arbitration clause in case of disagreements.',
      sentenceID: 'Kontrak tersebut mencakup klausul arbitrase jika terjadi perselisihan.',
      sentenceEN2: 'Singapore is a major international arbitration hub in Southeast Asia.',
      sentenceID2: 'Singapura adalah pusat arbitrase internasional utama di Asia Tenggara.',
      tipEN: 'Singapore International Arbitration Centre (SIAC) is widely used in Batam-Singapore disputes.',
      tipID: 'Pusat Arbitrase Internasional Singapura (SIAC) banyak digunakan dalam sengketa Batam-Singapura.',
    },
    {
      id: 'compliance',
      week: 18,
      word: 'COMPLIANCE',
      phonetic: '/kəmˈplaɪ.əns/',
      meaningID: 'Kepatuhan / Pemenuhan Regulasi',
      meaningEN: 'The act of following rules, regulations, and standards',
      sentenceEN: 'Our company passed the annual compliance audit with no findings.',
      sentenceID: 'Perusahaan kami lulus audit kepatuhan tahunan tanpa temuan.',
      sentenceEN2: 'Export compliance is essential when shipping from Batam to Singapore.',
      sentenceID2: 'Kepatuhan ekspor sangat penting saat pengiriman dari Batam ke Singapura.',
      tipEN: '"Compliance" is non-negotiable in regulated industries — use it confidently.',
      tipID: '"Compliance" tidak bisa ditawar dalam industri yang diatur — gunakan dengan percaya diri.',
    },
    {
      id: 'capacity',
      week: 17,
      word: 'CAPACITY',
      phonetic: '/kəˈpæs.ɪ.ti/',
      meaningID: 'Kapasitas / Kemampuan Produksi',
      meaningEN: 'The maximum amount that can be produced, held, or dealt with',
      sentenceEN: 'Our factory is currently running at 90% capacity.',
      sentenceID: 'Pabrik kami saat ini beroperasi pada kapasitas 90%.',
      sentenceEN2: 'We need to expand our storage capacity before the peak season.',
      sentenceID2: 'Kita perlu memperluas kapasitas penyimpanan sebelum musim puncak.',
      tipEN: '"Full capacity" means maximum output. "Spare capacity" means room to produce more.',
      tipID: '"Full capacity" berarti output maksimum. "Spare capacity" berarti ruang untuk produksi lebih banyak.',
    },
    {
      id: 'leverage_medium',
      week: 15,
      word: 'LEVERAGE',
      phonetic: '/ˈlev.ər.ɪdʒ/',
      meaningID: 'Memanfaatkan / Memaksimalkan Keunggulan',
      meaningEN: 'To use something to maximum advantage in a negotiation or business situation',
      sentenceEN: 'We can leverage our factory location in Batam to offer competitive pricing.',
      sentenceID: 'Kita bisa memanfaatkan lokasi pabrik di Batam untuk menawarkan harga yang kompetitif.',
      sentenceEN2: 'They leveraged their existing network to secure the government contract.',
      sentenceID2: 'Mereka memanfaatkan jaringan yang ada untuk mendapatkan kontrak pemerintah.',
      tipEN: 'Common in sales and negotiation — "What can we leverage?" opens strategic thinking.',
      tipID: 'Umum dalam penjualan dan negosiasi — "What can we leverage?" membuka pemikiran strategis.',
    },
    {
      id: 'milestone',
      week: 11,
      word: 'MILESTONE',
      phonetic: '/ˈmaɪl.stəʊn/',
      meaningID: 'Tonggak Pencapaian / Tahapan Penting',
      meaningEN: 'A significant stage or event in the development of something',
      sentenceEN: 'Completing the factory audit is a major milestone for the project.',
      sentenceID: 'Menyelesaikan audit pabrik adalah tonggak pencapaian utama proyek ini.',
      sentenceEN2: 'We hit every milestone in the first phase of the expansion.',
      sentenceID2: 'Kami mencapai setiap tonggak pencapaian dalam fase pertama ekspansi.',
      tipEN: 'Project managers use milestones to track progress — learn to use this word naturally.',
      tipID: 'Manajer proyek menggunakan milestone untuk melacak kemajuan — pelajari cara menggunakan kata ini secara alami.',
    },
    {
      id: 'portfolio',
      week: 15,
      word: 'PORTFOLIO',
      phonetic: '/pɔːtˈfəʊ.li.əʊ/',
      meaningID: 'Portofolio / Kumpulan Karya atau Produk',
      meaningEN: 'A collection of work, investments, or products representing a person or company',
      sentenceEN: 'Our product portfolio covers electronics, plastics, and precision components.',
      sentenceID: 'Portofolio produk kami mencakup elektronik, plastik, dan komponen presisi.',
      sentenceEN2: 'She presented her portfolio to the Singapore venture capital firm.',
      sentenceID2: 'Dia mempresentasikan portofolionya kepada perusahaan modal ventura Singapura.',
      tipEN: '"Portfolio" is used for both products (range of offerings) and investments (assets held).',
      tipID: '"Portfolio" digunakan untuk produk (rangkaian penawaran) dan investasi (aset yang dimiliki).',
    },
    {
      id: 'turnaround',
      week: 14,
      word: 'TURNAROUND',
      phonetic: '/ˈtɜː.nə.raʊnd/',
      meaningID: 'Pemulihan / Waktu Penyelesaian / Perubahan Arah',
      meaningEN: 'The time taken to complete a process; or a significant positive change in performance',
      sentenceEN: 'Our turnaround time for custom orders is five business days.',
      sentenceID: 'Waktu penyelesaian kami untuk pesanan khusus adalah lima hari kerja.',
      sentenceEN2: 'The new management achieved a remarkable turnaround in just two quarters.',
      sentenceID2: 'Manajemen baru mencapai pemulihan yang luar biasa hanya dalam dua kuartal.',
      tipEN: '"Turnaround time" is critical in manufacturing and logistics — know it well.',
      tipID: '"Turnaround time" sangat penting dalam manufaktur dan logistik — pelajari dengan baik.',
    },
    {
      id: 'incentive',
      week: 18,
      word: 'INCENTIVE',
      phonetic: '/ɪnˈsen.tɪv/',
      meaningID: 'Insentif / Imbalan / Motivasi',
      meaningEN: 'Something that motivates someone to take action or work harder',
      sentenceEN: 'The company offers performance incentives for staff who exceed targets.',
      sentenceID: 'Perusahaan menawarkan insentif kinerja bagi staf yang melampaui target.',
      sentenceEN2: 'Tax incentives in Batam FTZ attract many foreign manufacturers.',
      sentenceID2: 'Insentif pajak di FTZ Batam menarik banyak produsen asing.',
      tipEN: 'Batam FTZ\'s tax incentives are a major selling point when pitching to international investors.',
      tipID: 'Insentif pajak FTZ Batam adalah poin penjualan utama saat pitching kepada investor internasional.',
    },
  ],

  high: [
    {
      id: 'synergy',
      week: 19,
      word: 'SYNERGY',
      phonetic: '/ˈsɪn.ə.dʒi/',
      meaningID: 'Sinergi / Efek Gabungan yang Lebih Besar',
      meaningEN: 'The combined effect of two or more elements working together that is greater than their separate effects',
      sentenceEN: 'The merger created real synergy between the two companies\' distribution networks.',
      sentenceID: 'Merger menciptakan sinergi nyata antara jaringan distribusi dua perusahaan.',
      sentenceEN2: 'We are pursuing this joint venture specifically for the operational synergies it offers.',
      sentenceID2: 'Kami mengejar usaha patungan ini khusus untuk sinergi operasional yang ditawarkannya.',
      tipEN: 'Overused in boardrooms — when you use it, back it up with specific examples.',
      tipID: 'Sering digunakan di ruang dewan — ketika menggunakannya, dukung dengan contoh spesifik.',
    },
    {
      id: 'acumen',
      week: 24,
      word: 'ACUMEN',
      phonetic: '/ˈæk.jʊ.mən/',
      meaningID: 'Ketajaman Bisnis / Kecerdasan Praktis',
      meaningEN: 'The ability to make good judgements and quick decisions in a particular domain',
      sentenceEN: 'Her financial acumen helped the company navigate the economic downturn.',
      sentenceID: 'Ketajaman keuangannya membantu perusahaan menavigasi penurunan ekonomi.',
      sentenceEN2: 'Business acumen is what separates good managers from great leaders.',
      sentenceID2: 'Ketajaman bisnis adalah yang membedakan manajer yang baik dari pemimpin yang hebat.',
      tipEN: '"Business acumen" on a CV or in an interview signals executive-level thinking.',
      tipID: '"Business acumen" di CV atau wawancara menandakan pemikiran tingkat eksekutif.',
    },
    {
      id: 'mitigate',
      week: 22,
      word: 'MITIGATE',
      phonetic: '/ˈmɪt.ɪ.ɡeɪt/',
      meaningID: 'Memitigasi / Mengurangi Risiko',
      meaningEN: 'To reduce the severity, seriousness, or painfulness of something',
      sentenceEN: 'We implemented backup suppliers to mitigate supply chain risk.',
      sentenceID: 'Kami menerapkan pemasok cadangan untuk memitigasi risiko rantai pasokan.',
      sentenceEN2: 'The legal team identified three clauses to mitigate contract exposure.',
      sentenceID2: 'Tim hukum mengidentifikasi tiga klausul untuk memitigasi eksposur kontrak.',
      tipEN: '"Mitigate risk" is the executive-level alternative to "reduce risk" — preferred in board presentations.',
      tipID: '"Mitigate risk" adalah alternatif tingkat eksekutif untuk "reduce risk" — disukai dalam presentasi dewan.',
    },
    {
      id: 'compelling',
      week: 6,
      word: 'COMPELLING',
      phonetic: '/kəmˈpel.ɪŋ/',
      meaningID: 'Meyakinkan / Sangat Menarik Perhatian',
      meaningEN: 'Evoking strong interest or attention; convincing and powerful',
      sentenceEN: 'The CFO delivered a compelling case for expanding into the Singapore market.',
      sentenceID: 'CFO menyampaikan argumen yang meyakinkan untuk ekspansi ke pasar Singapura.',
      sentenceEN2: 'We need a compelling narrative to attract tier-one investors.',
      sentenceID2: 'Kita membutuhkan narasi yang meyakinkan untuk menarik investor kelas satu.',
      tipEN: 'A "compelling argument" is stronger than "a good argument" — use it when presenting to executives.',
      tipID: '"Compelling argument" lebih kuat dari "a good argument" — gunakan saat presentasi kepada eksekutif.',
    },
    {
      id: 'paradigm',
      week: 21,
      word: 'PARADIGM',
      phonetic: '/ˈpær.ə.daɪm/',
      meaningID: 'Paradigma / Kerangka Pemikiran',
      meaningEN: 'A typical example or model of something; a fundamental framework of thinking',
      sentenceEN: 'Digital transformation represents a paradigm shift in how we do business.',
      sentenceID: 'Transformasi digital mewakili pergeseran paradigma dalam cara kita berbisnis.',
      sentenceEN2: 'The startup challenged the existing paradigm of industrial manufacturing.',
      sentenceID2: 'Startup tersebut menantang paradigma manufaktur industri yang ada.',
      tipEN: '"Paradigm shift" describes a fundamental change in approach — use sparingly for maximum impact.',
      tipID: '"Paradigm shift" menggambarkan perubahan mendasar dalam pendekatan — gunakan hemat untuk dampak maksimum.',
    },
    {
      id: 'trajectory',
      week: 20,
      word: 'TRAJECTORY',
      phonetic: '/trəˈdʒek.tər.i/',
      meaningID: 'Lintasan / Arah Perkembangan',
      meaningEN: 'The path of development or progress of something over time',
      sentenceEN: 'The company\'s growth trajectory has been impressive over the last five years.',
      sentenceID: 'Lintasan pertumbuhan perusahaan sangat mengesankan selama lima tahun terakhir.',
      sentenceEN2: 'We need to change our cost trajectory before the next funding round.',
      sentenceID2: 'Kita perlu mengubah lintasan biaya sebelum putaran pendanaan berikutnya.',
      tipEN: '"Growth trajectory" is a power phrase in investor presentations and executive reports.',
      tipID: '"Growth trajectory" adalah frasa kuat dalam presentasi investor dan laporan eksekutif.',
    },
    {
      id: 'arbitrage',
      week: 19,
      word: 'ARBITRAGE',
      phonetic: '/ˈɑː.bɪ.trɑːʒ/',
      meaningID: 'Arbitrase / Memanfaatkan Perbedaan Harga Atau Regulasi',
      meaningEN: 'The practice of exploiting price or regulatory differences between two markets',
      sentenceEN: 'Many companies in Batam leverage regulatory arbitrage between Indonesia and Singapore.',
      sentenceID: 'Banyak perusahaan di Batam memanfaatkan arbitrase regulasi antara Indonesia dan Singapura.',
      sentenceEN2: 'Labour arbitrage remains a key advantage for Batam-based manufacturers.',
      sentenceID2: 'Arbitrase tenaga kerja tetap menjadi keunggulan utama bagi produsen berbasis di Batam.',
      tipEN: 'Batam\'s FTZ is literally built on regulatory and labour arbitrage with Singapore.',
      tipID: 'FTZ Batam secara harfiah dibangun di atas arbitrase regulasi dan tenaga kerja dengan Singapura.',
    },
    {
      id: 'due_diligence',
      week: 7,
      word: 'DUE DILIGENCE',
      phonetic: '/djuː ˈdɪl.ɪ.dʒəns/',
      meaningID: 'Uji Tuntas / Investigasi Mendalam Sebelum Keputusan',
      meaningEN: 'A comprehensive appraisal of a business undertaken before signing a contract or investment',
      sentenceEN: 'The Singapore investor is conducting due diligence on our Batam operations.',
      sentenceID: 'Investor Singapura sedang melakukan uji tuntas terhadap operasi Batam kami.',
      sentenceEN2: 'We must complete due diligence before finalising the acquisition.',
      sentenceID2: 'Kita harus menyelesaikan uji tuntas sebelum menyelesaikan akuisisi.',
      tipEN: '"Due diligence" is a legal and financial term — knowing it signals business sophistication.',
      tipID: '"Due diligence" adalah istilah hukum dan keuangan — mengetahuinya menandakan kecanggihan bisnis.',
    },
    {
      id: 'monetise',
      week: 15,
      word: 'MONETISE',
      phonetic: '/ˈmʌn.ɪ.taɪz/',
      meaningID: 'Memonetisasi / Mengubah Menjadi Pendapatan',
      meaningEN: 'To earn revenue from something, especially an asset, platform, or capability',
      sentenceEN: 'The company is looking for ways to monetise its proprietary manufacturing data.',
      sentenceID: 'Perusahaan mencari cara untuk memonetisasi data manufaktur miliknya.',
      sentenceEN2: 'How can we monetise the excess capacity at our Batam plant?',
      sentenceID2: 'Bagaimana kita bisa memonetisasi kapasitas berlebih di pabrik Batam kita?',
      tipEN: '"Monetise" is essential vocabulary in startup, tech, and investment conversations.',
      tipID: '"Monetise" adalah kosakata penting dalam percakapan startup, teknologi, dan investasi.',
    },
    {
      id: 'scalable',
      week: 21,
      word: 'SCALABLE',
      phonetic: '/ˈskeɪ.lə.bəl/',
      meaningID: 'Skalabel / Dapat Berkembang Sesuai Kebutuhan',
      meaningEN: 'Able to be easily expanded or adapted to a larger size or different needs',
      sentenceEN: 'We need a scalable solution that works for 500 employees, not just 50.',
      sentenceID: 'Kita membutuhkan solusi yang skalabel yang berhasil untuk 500 karyawan, bukan hanya 50.',
      sentenceEN2: 'Their business model is highly scalable across Southeast Asian markets.',
      sentenceID2: 'Model bisnis mereka sangat skalabel di seluruh pasar Asia Tenggara.',
      tipEN: '"Scalable" is a high-value word in tech, operations, and investment discussions.',
      tipID: '"Scalable" adalah kata bernilai tinggi dalam diskusi teknologi, operasional, dan investasi.',
    },
    {
      id: 'articulate',
      week: 23,
      word: 'ARTICULATE',
      phonetic: '/ɑːˈtɪk.jʊ.lɪt/',
      meaningID: 'Artikulatif / Mampu Menyampaikan Ide dengan Jelas',
      meaningEN: 'Able to express thoughts and ideas clearly and effectively',
      sentenceEN: 'He is highly articulate — he explained the technical specs in plain language.',
      sentenceID: 'Dia sangat artikulatif — dia menjelaskan spesifikasi teknis dalam bahasa yang mudah dipahami.',
      sentenceEN2: 'An articulate leader earns more trust from international partners.',
      sentenceID2: 'Pemimpin yang artikulatif mendapatkan lebih banyak kepercayaan dari mitra internasional.',
      tipEN: 'Being described as "articulate" in English is a significant professional compliment.',
      tipID: 'Digambarkan sebagai "articulate" dalam bahasa Inggris adalah pujian profesional yang signifikan.',
    },
    {
      id: 'incumbent',
      week: 24,
      word: 'INCUMBENT',
      phonetic: '/ɪnˈkʌm.bənt/',
      meaningID: 'Petahana / Yang Sedang Menjabat',
      meaningEN: 'The current holder of an office or position; necessary as a duty',
      sentenceEN: 'As the incumbent supplier, we must defend our position against new competitors.',
      sentenceID: 'Sebagai pemasok petahana, kita harus mempertahankan posisi dari pesaing baru.',
      sentenceEN2: 'It is incumbent upon the leadership to communicate the strategy clearly.',
      sentenceID2: 'Ini merupakan kewajiban kepemimpinan untuk mengkomunikasikan strategi dengan jelas.',
      tipEN: '"Incumbent" has two meanings: the current holder of a role, or something that is a duty ("it is incumbent upon...").',
      tipID: '"Incumbent" memiliki dua makna: pemegang jabatan saat ini, atau sesuatu yang merupakan kewajiban ("it is incumbent upon...").',
    },
    {
      id: 'disruptive',
      week: 21,
      word: 'DISRUPTIVE',
      phonetic: '/dɪsˈrʌp.tɪv/',
      meaningID: 'Disruptif / Mengubah Secara Fundamental',
      meaningEN: 'Causing fundamental change to an industry or established way of doing things',
      sentenceEN: 'Electric vehicles are a disruptive force in the global automotive supply chain.',
      sentenceID: 'Kendaraan listrik adalah kekuatan disruptif dalam rantai pasokan otomotif global.',
      sentenceEN2: 'Batam manufacturers need to prepare for disruptive automation technologies.',
      sentenceID2: 'Produsen Batam perlu mempersiapkan diri untuk teknologi otomasi yang disruptif.',
      tipEN: '"Disruptive innovation" is a specific concept by Clayton Christensen — know the context.',
      tipID: '"Disruptive innovation" adalah konsep spesifik oleh Clayton Christensen — ketahui konteksnya.',
    },
    {
      id: 'holistic',
      week: 20,
      word: 'HOLISTIC',
      phonetic: '/həˈlɪs.tɪk/',
      meaningID: 'Holistik / Menyeluruh dan Terintegrasi',
      meaningEN: 'Dealing with the whole system rather than individual parts in isolation',
      sentenceEN: 'We need a holistic approach to resolving the supply chain bottlenecks.',
      sentenceID: 'Kita membutuhkan pendekatan holistik untuk menyelesaikan hambatan rantai pasokan.',
      sentenceEN2: 'The consultant recommended a holistic review of our HR and operational processes.',
      sentenceID2: 'Konsultan merekomendasikan tinjauan holistik terhadap proses SDM dan operasional kami.',
      tipEN: '"Holistic approach" signals systems thinking — highly valued at the C-suite level.',
      tipID: '"Holistic approach" menandakan pemikiran sistem — sangat dihargai di tingkat C-suite.',
    },
    {
      id: 'divestiture',
      week: 16,
      word: 'DIVESTITURE',
      phonetic: '/daɪˈves.tɪ.tʃər/',
      meaningID: 'Divestasi / Pelepasan Aset',
      meaningEN: 'The process of selling off a subsidiary, business unit, or asset',
      sentenceEN: 'The board approved the divestiture of the non-core logistics division.',
      sentenceID: 'Dewan menyetujui divestasi divisi logistik non-inti.',
      sentenceEN2: 'The divestiture was part of a broader strategy to focus on core manufacturing.',
      sentenceID2: 'Divestasi tersebut merupakan bagian dari strategi yang lebih luas untuk fokus pada manufaktur inti.',
      tipEN: 'Know the difference: "divestiture" = selling assets; "acquisition" = buying assets.',
      tipID: 'Ketahui perbedaannya: "divestiture" = menjual aset; "acquisition" = membeli aset.',
    },
    {
      id: 'perpetuate',
      week: 25,
      word: 'PERPETUATE',
      phonetic: '/pəˈpetʃ.u.eɪt/',
      meaningID: 'Melanggengkan / Mempertahankan Secara Terus-Menerus',
      meaningEN: 'To make something continue indefinitely; often used when discussing cycles or patterns',
      sentenceEN: 'We must avoid practices that perpetuate inefficiency in the supply chain.',
      sentenceID: 'Kita harus menghindari praktik yang melanggengkan inefisiensi dalam rantai pasokan.',
      sentenceEN2: 'Strong training programmes perpetuate a culture of excellence.',
      sentenceID2: 'Program pelatihan yang kuat melanggengkan budaya keunggulan.',
      tipEN: 'Used both positively ("perpetuate excellence") and negatively ("perpetuate problems").',
      tipID: 'Digunakan secara positif ("perpetuate excellence") dan negatif ("perpetuate problems").',
    },
    {
      id: 'juxtapose',
      week: 25,
      word: 'JUXTAPOSE',
      phonetic: '/ˈdʒʌk.stə.pəʊz/',
      meaningID: 'Membandingkan Secara Berdampingan / Mempertentangkan',
      meaningEN: 'To place two things close together for the purpose of comparison or contrast',
      sentenceEN: 'The analyst juxtaposed our Batam costs with Singapore operational data.',
      sentenceID: 'Analis membandingkan biaya Batam kami dengan data operasional Singapura.',
      sentenceEN2: 'Juxtaposing the two strategies makes the advantages of each very clear.',
      sentenceID2: 'Membandingkan dua strategi secara berdampingan membuat keunggulan masing-masing sangat jelas.',
      tipEN: 'Used in analytical writing and high-level presentations to show sophisticated thinking.',
      tipID: 'Digunakan dalam penulisan analitis dan presentasi tingkat tinggi untuk menunjukkan pemikiran yang canggih.',
    },
    {
      id: 'impetus',
      week: 26,
      word: 'IMPETUS',
      phonetic: '/ˈɪm.pɪ.təs/',
      meaningID: 'Dorongan / Momentum Awal',
      meaningEN: 'Something that makes a process or activity happen or happen faster',
      sentenceEN: 'The new trade agreement provided the impetus for further regional expansion.',
      sentenceID: 'Perjanjian perdagangan baru memberikan dorongan untuk ekspansi regional lebih lanjut.',
      sentenceEN2: 'The CEO\'s vision was the impetus behind the entire digital transformation.',
      sentenceID2: 'Visi CEO adalah dorongan di balik seluruh transformasi digital.',
      tipEN: '"Impetus" elevates your language from "reason" or "push" — use it in formal reports.',
      tipID: '"Impetus" meningkatkan bahasa Anda dari "reason" atau "push" — gunakan dalam laporan formal.',
    },
    {
      id: 'propensity',
      week: 26,
      word: 'PROPENSITY',
      phonetic: '/prəˈpen.sɪ.ti/',
      meaningID: 'Kecenderungan / Tendensi Alami',
      meaningEN: 'A natural inclination or tendency to behave in a particular way',
      sentenceEN: 'There is a propensity among Batam manufacturers to underinvest in English training.',
      sentenceID: 'Ada kecenderungan di antara produsen Batam untuk kurang berinvestasi dalam pelatihan bahasa Inggris.',
      sentenceEN2: 'High-performing teams have a propensity to over-communicate rather than under-communicate.',
      sentenceID2: 'Tim berprestasi tinggi cenderung berkomunikasi berlebihan daripada kurang berkomunikasi.',
      tipEN: '"Propensity" is favoured in academic and executive writing — signals rigour.',
      tipID: '"Propensity" disukai dalam penulisan akademis dan eksekutif — menandakan ketelitian.',
    },
    {
      id: 'commensurate',
      week: 24,
      word: 'COMMENSURATE',
      phonetic: '/kəˈmen.sər.ɪt/',
      meaningID: 'Sebanding / Setara / Sesuai Dengan',
      meaningEN: 'Corresponding in size or degree; proportionate',
      sentenceEN: 'Salary will be commensurate with experience and qualifications.',
      sentenceID: 'Gaji akan sebanding dengan pengalaman dan kualifikasi.',
      sentenceEN2: 'The risk taken should be commensurate with the expected return.',
      sentenceID2: 'Risiko yang diambil harus sebanding dengan imbal hasil yang diharapkan.',
      tipEN: 'Very common in job postings and financial presentations — know this word cold.',
      tipID: 'Sangat umum dalam lowongan kerja dan presentasi keuangan — hafalkan kata ini.',
    },
  ],
}
